import {escapeHtml as esc} from './scenario-display.js';
export function installAbyssalLibrary({host,catalog,api,render,onLocate,onInfo}){
 const footer=host.querySelector('footer'),normalHint=footer.textContent;
 const root=host.querySelector('#tree'),search=host.querySelector('#search'),groups=new Set(catalog.filter(t=>t.en.includes('Abyssal')&&['high','mid','low'].includes(t.kind)).map(t=>t.group));
 const eligible=t=>t&&['high','mid','low'].includes(t.kind)&&groups.has(t.group)&&!t.en.includes('Abyssal');
 let active=false,records=[],loaded=false,loading=false,error='',located=null;const open=new Set(),views={normal:{query:'',scroll:0},abyss:{query:'',scroll:0}};
 const tabs=document.createElement('div');tabs.className='equipment-library-tabs';tabs.innerHTML='<button data-view="normal" aria-pressed="true">普通装备</button><button data-view="abyss" aria-pressed="false">深渊装备</button>';host.querySelector('.search').before(tabs);
 async function load(){if(loading)return;loading=true;error='';try{records=await api('abyssal-instances');loaded=true}catch(e){error=e.message}finally{loading=false;if(active)render()}}
 function switchTo(value){if(active===value)return;views[active?'abyss':'normal']={query:search.value,scroll:root.scrollTop};active=value;footer.textContent=active?'点击编辑实例 · 右键管理':normalHint;const view=views[active?'abyss':'normal'];search.value=view.query;tabs.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String((b.dataset.view==='abyss')===active)));render();root.scrollTop=view.scroll;if(active)load();}
 tabs.querySelectorAll('button').forEach(b=>b.onclick=()=>switchTo(b.dataset.view==='abyss'));
 const path=t=>[...t.path,t.meta||'科技 I'];
 function reveal(t){let key='';for(const part of path(t)){key+='/'+part;open.add(key)}open.add('base/'+t.id);located=t.id;}
 function locate(t){onLocate();reveal(t);if(!active)switchTo(true);search.value='';render();if(!loaded)load();}
 function edit(t,record=null,copy=false){
  const dialog=document.createElement('dialog');dialog.className='abyssal-editor character-action-dialog';const current=record&&!copy?record:null;
  dialog.innerHTML='<form><div class="flow-head"><b>'+esc(current?'编辑深渊实例':'创建深渊实例')+'</b><button type="button" data-close aria-label="关闭深渊实例编辑">×</button></div><div class="flow-body"><div class="abyssal-origin"><img src="https://images.evetech.net/types/'+t.id+'/icon?size=64" alt=""><span>'+esc(t.name)+'</span></div><label>实例名称<input aria-label="深渊实例名称" maxlength="100" required></label><label>备注<textarea aria-label="深渊实例备注" maxlength="1000" rows="3" placeholder="例如：用途、来源或待录入的变异数据"></textarea></label><p class="profile-note">待录入变异属性 · 当前保存为实例草稿</p><p class="abyssal-error" role="status"></p><button type="submit">保存到深渊库</button></div></form>';
  document.body.append(dialog);const input=dialog.querySelector('input'),notes=dialog.querySelector('textarea');input.value=record?record.name+(copy?' · 副本':''):t.name+' · 深渊 '+(records.filter(x=>x.baseTypeId===t.id).length+1);notes.value=record?.notes||'';
  dialog.querySelector('[data-close]').onclick=()=>dialog.close();dialog.onclose=()=>dialog.remove();dialog.querySelector('form').onsubmit=async e=>{e.preventDefault();const button=dialog.querySelector('[type=submit]');button.disabled=true;try{const saved=await api('abyssal-instance',{...(current?{id:current.id,revision:current.revision}:{}),baseTypeId:t.id,name:input.value.trim(),notes:notes.value});records=records.filter(x=>x.id!==saved.id).concat(saved);loaded=true;reveal(t);search.value='';render();dialog.close();}catch(e){dialog.querySelector('.abyssal-error').textContent=e.message}finally{button.disabled=false}};dialog.showModal();input.focus();input.select();
 }
 function menu(event,t,record=null){event.preventDefault();event.stopPropagation();document.querySelector('.abyssal-menu')?.remove();const popup=document.createElement('div');popup.className='abyssal-menu scenario-quick-menu';popup.role='menu';popup.setAttribute('popover','auto');
  const actions=record?[['编辑实例',()=>edit(t,record)],['复制实例',()=>edit(t,record,true)],['原装备详细信息',()=>onInfo(t)],['删除实例',()=>remove(t,record)]]:[['创建深渊实例',()=>edit(t)],['原装备详细信息',()=>onInfo(t)]];
  for(const [label,fn] of actions){const b=document.createElement('button');b.role='menuitem';b.textContent=label;b.onclick=()=>{popup.hidePopover();popup.remove();fn()};popup.append(b)}popup.addEventListener('toggle',e=>{if(e.newState==='closed')popup.remove()});document.body.append(popup);popup.showPopover();const r=event.currentTarget.getBoundingClientRect(),x=event.type==='keydown'?r.left:event.clientX,y=event.type==='keydown'?r.bottom:event.clientY;popup.style.left=Math.max(8,Math.min(x,innerWidth-popup.offsetWidth-8))+'px';popup.style.top=Math.max(8,Math.min(y,innerHeight-popup.offsetHeight-8))+'px';popup.querySelector('button').focus();
 }
 function remove(t,record){const d=document.createElement('dialog');d.className='character-action-dialog';d.innerHTML='<div class="flow-head"><b>删除深渊实例</b></div><div class="flow-body"><p>'+esc(record.name)+'</p><p role="status"></p><button data-cancel>取消</button><button data-delete>删除</button></div>';document.body.append(d);d.querySelector('[data-cancel]').onclick=()=>d.close();d.onclose=()=>d.remove();d.querySelector('[data-delete]').onclick=async()=>{const b=d.querySelector('[data-delete]');b.disabled=true;try{await api('abyssal-instance/delete',{id:record.id,revision:record.revision});records=records.filter(x=>x.id!==record.id);render();d.close()}catch(e){d.querySelector('[role=status]').textContent=e.message;b.disabled=false}};d.showModal();}
 function draw(items,q){
  if(!active)return false;if(!loaded&&!loading&&!error)load();const scroll=root.scrollTop;
  if(!loaded){root.innerHTML='<div class="hint">'+esc(error||'正在读取深渊库…')+'</div>';if(error){const b=document.createElement('button');b.textContent='重试';b.onclick=load;root.append(b)}return true;}
  const bases=items.filter(eligible),tree={};for(const t of bases){let n=tree;for(const part of path(t))n=n[part]??={};(n.items??=[]).push(t)}
  const branch=(node,prefix='')=>Object.entries(node).map(([key,value])=>{if(key==='items')return value.map(t=>{const entries=records.filter(r=>r.baseTypeId===t.id&&(!q||(r.name+' '+r.notes).toLowerCase().includes(q)||(t.name+' '+t.en+' '+t.path.join(' ')).toLowerCase().includes(q))),expanded=q||open.has('base/'+t.id);return '<details class="abyssal-base" data-open-key="base/'+t.id+'" '+(expanded?'open':'')+'><summary data-base="'+t.id+'"><img src="https://images.evetech.net/types/'+t.id+'/icon?size=64" alt=""><span>'+esc(t.name)+'</span><small>'+entries.length+'</small></summary>'+(expanded?entries.map(r=>'<button class="abyssal-instance" data-instance="'+esc(r.id)+'" title="'+esc(r.notes||'待录入变异属性')+'"><span>◇ '+esc(r.name)+'</span><small>待录入属性</small></button>').join('')+'<button class="abyssal-create" data-create="'+t.id+'">＋ 创建深渊实例</button>':'')+'</details>';}).join('');const p=prefix+'/'+key,expanded=q||open.has(p);return '<details data-open-key="'+esc(p)+'" '+(expanded?'open':'')+'><summary>'+esc(key)+'</summary>'+(expanded?branch(value,p):'')+'</details>';}).join('');
  root.innerHTML='<div class="abyssal-library-note">实例库 · 变异属性待接入</div>'+branch(tree)+(bases.length?'':'<div class="hint">当前筛选下没有原装备。</div>');host.querySelector('#count').textContent=records.filter(r=>bases.some(t=>t.id===r.baseTypeId)).length+' 个实例';root.scrollTop=scroll;
  root.querySelectorAll('summary').forEach(s=>{s.onclick=e=>{e.preventDefault();const key=s.parentElement.dataset.openKey;if(q){s.parentElement.open=!s.parentElement.open;return;}if(open.has(key))open.delete(key);else open.add(key);render()};if(s.dataset.base){const t=catalog.find(t=>t.id===Number(s.dataset.base));s.oncontextmenu=e=>menu(e,t);s.onkeydown=e=>{if(e.key==='ContextMenu'||e.shiftKey&&e.key==='F10')menu(e,t)}}});
  root.querySelectorAll('[data-create]').forEach(b=>b.onclick=()=>edit(catalog.find(t=>t.id===Number(b.dataset.create))));root.querySelectorAll('[data-instance]').forEach(b=>{const record=records.find(r=>r.id===b.dataset.instance),t=catalog.find(t=>t.id===record.baseTypeId);b.onclick=()=>edit(t,record);b.oncontextmenu=e=>menu(e,t,record);b.onkeydown=e=>{if(e.key==='ContextMenu'||e.shiftKey&&e.key==='F10')menu(e,t,record)}});
  if(located){const target=root.querySelector('[data-base="'+located+'"]');if(target){target.classList.add('located');target.scrollIntoView({block:'nearest'});located=null;}}
  return true;
 }
 return {get active(){return active},eligible,locate,draw,matches(t,q){return active&&records.some(r=>r.baseTypeId===t.id&&(r.name+' '+r.notes).toLowerCase().includes(q))}};
}
