from pathlib import Path
p=Path('build-catalog.py');s=p.read_text(encoding='utf-8-sig');s=s.replace("out=[];icons={}", "out=[];icons={};metas={m['_key']:m['name'].get('zh',m['name']['en']) for m in read('metaGroups')}")
s=s.replace("if not kind:continue", "if not kind:continue\n if kind in ['high','mid','low','rig'] and category!=7:continue")
s=s.replace("kind=kind,path=names,", "kind=kind,meta=metas.get(t.get('metaGroupID',1),'科技 I'),path=names or ['未列入市场'],")
p.write_text(s,encoding='utf-8')
p=Path('app.js');s=p.read_text(encoding='utf-8');s=s.replace("import {mountStats} from './stats-view.js';\n",'')
s=s.replace("[t.attrs['422']===2?'科技 II':'科技 I']", "[t.meta||'科技 I']")
s=s.replace("function scheduleAnalysis(){report=null;", "function scheduleAnalysis(){$('.inspector').classList.add('calculating');")
s=s.replace("report=result;$('#engine-status')", "report=result;$('.inspector').classList.remove('calculating');$('#engine-status')")
s=s.replace("$('#engine-status').textContent='计算失败';", "$('.inspector').classList.remove('calculating');$('#engine-status').textContent='计算失败 · 当前数据未更新';")
a=s.index("const active=slots.filter",s.index('function renderResources'));b=s.index('\nfunction hardpoints',a)
s=s[:a]+"$('#resources').innerHTML='<p class=\"profile-note\">等待计算服务…</p>'}\n"+s[b:]
a=s.index('function renderShipStats(){');b=s.index('let infoOrigin',a)
s=s[:a]+"function renderShipStats(){if(report){renderEngineStats();return}$('#ship-stats').innerHTML='<div class=\"stat-block profile-note\">正在计算装配属性…</div>'}\n"+s[b:]
s=s.replace("fitRecord=saved;localStorage", "fitRecord={...fitRecord,id:saved.id,revision:saved.revision,updatedAt:saved.updatedAt};localStorage")
s=s.replace("async function persistFit(){", "let saving=Promise.resolve();\nfunction persistFit(){const task=saving.catch(()=>{}).then(writeFit);saving=task;return task}\nasync function writeFit(){")
s=s.replace("const saved=await api('save',currentFit());", "const input=currentFit(),saved=await api('save',input);")
s=s.replace("$('#save').textContent='已保存 · '+new Date(saved.updatedAt).toLocaleTimeString();", "$('#save').textContent=JSON.stringify(input.slots)===JSON.stringify(slots)&&JSON.stringify(input.skills)===JSON.stringify(fitRecord.skills)?'已保存 · '+new Date(saved.updatedAt).toLocaleTimeString():'已保存上一版本 · 当前改动待保存';")
p.write_text(s,encoding='utf-8')
p=Path('index.html');s=p.read_text(encoding='utf-8').replace('EVE FitLab · 控件实验室','EVE FitLab · 装配工作台').replace('SDE 原始资源演示<br>未计入角色技能与模块加成，不作为装配有效性结论。','装配计算服务连接中…');p.write_text(s,encoding='utf-8')
