from pathlib import Path
r=Path(r'D:/IT/EVE/EdenOsRewrite/src/application-csharp/EdenOS.Application/Fitting/Dogma')
p=r/'Engine/FittingCalculator.cs';s=p.read_text(encoding='utf-8');s=s.replace('internal sealed record FittingModuleCombatProjection\n{','internal sealed record FittingModuleCombatProjection\n{\n    public decimal CpuUsage { get; init; }\n    public decimal PowergridUsage { get; init; }');s=s.replace('                CycleTimeSeconds = RoundToDecimal(cycleTimeMs / 1000d),','''                CpuUsage = string.Equals(module.State, "offline", StringComparison.OrdinalIgnoreCase) ? 0 : RoundToDecimal(GetEffectiveTypeAttributeValue(TargetObjectKind.Item, moduleIndex, moduleTypeId, "cpu", skills, dogmaContext, sources, effectCache, inProgress, modifierCandidateCache, requiredSkillCache)),
                PowergridUsage = string.Equals(module.State, "offline", StringComparison.OrdinalIgnoreCase) ? 0 : RoundToDecimal(GetEffectiveTypeAttributeValue(TargetObjectKind.Item, moduleIndex, moduleTypeId, "power", skills, dogmaContext, sources, effectCache, inProgress, modifierCandidateCache, requiredSkillCache)),
                CycleTimeSeconds = RoundToDecimal(cycleTimeMs / 1000d),''');p.write_text(s,encoding='utf-8')
p=r/'DogmaFitAdapter.cs';s=p.read_text(encoding='utf-8').replace('                    DamagePerSecond = projection.DamagePerSecond,','                    CpuUsage = projection.CpuUsage,\n                    PowergridUsage = projection.PowergridUsage,\n                    DamagePerSecond = projection.DamagePerSecond,');p.write_text(s,encoding='utf-8')
p=Path('item-info.js');s=p.read_text(encoding='utf-8');s=s.replace("const results={};if(computed){", "const results={};if(computed){computed={...computed};if(computed.charge){for(const [key,bonus] of [['damagePerSecond','damagePerSecondBonus'],['volleyDamage','volleyDamageBonus']])computed[key]=(computed[key]||0)+(computed.charge[bonus]||0);for(const [key,bonus] of [['damageProfilePerSecond','damageProfileBonus'],['volleyDamageProfile','volleyDamageProfileBonus']])computed[key]=Object.fromEntries(['em','thermal','kinetic','explosive'].map(k=>[k,(computed[key]?.[k]||0)+(computed.charge[bonus]?.[k]||0)]));}")
s=s.replace("const [group,label,unit]=projected[key];", "const [group,label,unit]=projected[key];if(group==='导弹'&&computed.applicationKind!=='Missile')continue;")
s=s.replace("if(a.unitID===116)", "if(a.unitID===117)return ({1:'小型',2:'中型',3:'大型',4:'旗舰级'})[v]||number(v);if(a.unitID===116)")
p.write_text(s,encoding='utf-8')
