import {analysisStatusText} from './analysis-status.js';
import {scanFitImage,decodeFitCodes} from './fit-image-code.js';
export function showImageImport({catalog,calculate,save,onSaved}){
 const dialog=document.createElement('dialog');dialog.className='share-dialog image-import-dialog';dialog.innerHTML='<div class="flow-head"><b>从分享图片导入装配</b><button aria-label="关闭图片导入">×</button></div><div class="image-import-body"><p>选择包含完整装配码的图片，也可以拖入图片或粘贴截图。多张截图可分批补充。</p><input type="file" accept="image/png,image/jpeg,image/webp,image/bmp" multiple aria-label="选择装配图片"><p class="image-import-status" role="status">图片在本机识别，不上传。</p><div class="image-import-summary"></div><p>仅支持含 EVE FitLab 装配码的新分享图。截图请保留二维码四周白边；画面过小时可单独截取尾部。外部靶标、传电和毁电关联需重新设置。</p><button class="image-import-reset">清空重新识别</button><button class="image-import-save" disabled>导入为新装配</button></div>';document.body.append(dialog);dialog.showModal();const status=dialog.querySelector('.image-import-status'),summary=dialog.querySelector('.image-import-summary'),button=dialog.querySelector('.image-import-save');let codes=new Set(),fit=null,busy=false;dialog.querySelector('.flow-head button').onclick=()=>dialog.close();dialog.addEventListener('close',()=>dialog.remove(),{once:true});
 async function read(files){if(busy||!dialog.open)return;if(files.length>16){status.textContent='每次最多选择 16 张图片';return;}busy=true;fit=null;button.disabled=true;summary.replaceChildren();try{for(const file of files){status.textContent='正在识别 '+file.name+'…';for(const code of await scanFitImage(file))codes.add(code);if(!dialog.open)return;}status.textContent='正在校验装配数据…';const decoded=await decodeFitCodes([...codes],catalog);const report=await calculate(decoded);if(!dialog.open)return;fit=decoded;const title=document.createElement('h3');title.textContent=fit.name;const info=document.createElement('p');info.textContent=(catalog.find(t=>t.id===fit.shipId)?.name||'')+' · '+fit.slots.filter(s=>s.item).length+' 件装备 · '+fit.drones.reduce((n,e)=>n+e.quantity,0)+' 架无人机 · '+fit.skills.length+' 项技能';summary.replaceChildren(title,info);status.textContent='识别成功，'+analysisStatusText(report)+'。将创建新草稿，不覆盖已有记录。';button.disabled=false;}catch(e){status.textContent=e.message;}finally{busy=false}}
 dialog.querySelector('input').onchange=e=>read([...e.target.files]);dialog.ondragover=e=>{e.preventDefault()};dialog.ondrop=e=>{e.preventDefault();read([...e.dataTransfer.files])};dialog.onpaste=e=>{const files=[...e.clipboardData.files];if(files.length){e.preventDefault();read(files)}};
 dialog.querySelector('.image-import-reset').onclick=()=>{if(busy)return;codes.clear();fit=null;button.disabled=true;summary.replaceChildren();dialog.querySelector('input').value='';status.textContent='已清空，可以选择另一份装配图片。'};
 button.onclick=async()=>{if(!fit)return;button.disabled=true;try{const record=await save(fit);onSaved(record);dialog.close()}catch(e){status.textContent=e.message;button.disabled=false}};
}
