from pathlib import Path
p=Path('app.js');s=p.read_text(encoding='utf-8');s=s.replace("fetch('./data/catalog.json')","fetch('./data/full-catalog.json')")
s=s.replace("const $=s=>document.querySelector(s), byId=id=>catalog.find(t=>t.id===Number(id)), ship=byId(587);", "const $=s=>document.querySelector(s), typeIndex=new Map(catalog.map(t=>[t.id,t])), byId=id=>typeIndex.get(Number(id));\nlet ship=byId(587),fitRecord={name:'裂谷级 · 我的装配',shipId:587,skills:[],characterName:'无技能 · 基础对照'},report=null,analysisVersion=0,analysisTimer;\nconst treeOpen=new Set();")
s=s.replace("counts={high:ship.attrs['14'],mid:ship.attrs['13'],low:ship.attrs['12'],rig:ship.attrs['1137']}", "counts={high:ship.attrs['14']||0,mid:ship.attrs['13']||0,low:ship.attrs['12']||0,rig:ship.attrs['1137']||0}")
s=s.replace("t.kind!=='ship'", "!['ship','skill'].includes(t.kind)")
s=s.replace("closed=new Set([...root.querySelectorAll('details')].filter(d=>!d.open).map(d=>d.dataset.path))", "closed=new Set()")
a=s.index(' const branch=(n,path=');b=s.index("root.scrollTop=scroll;",a)+len('root.scrollTop=scroll;')
s=s[:a]+''' const branch=(n,path='')=>Object.entries(n).map(([k,v])=>k==='_items'?v.map(t=>`<div class="item" draggable="true" tabindex="0" role="button" data-id="${t.id}" aria-label="${esc(t.name)}">${img(t)}<span>${esc(t.name)}</span><em>${t.en.endsWith(' II')?'II':''}</em></div>`).join(''):(()=>{const key=path+'/'+k,open=!!q||treeOpen.has(key);return `<details data-path="${esc(key)}" ${open?'open':''}><summary>${marketIcons[key]?`<img class="tree-icon" src="${marketIcons[key]}" alt="">`:''}${esc(k)}</summary>${open?branch(v,key):''}</details>`})()).join('');root.innerHTML=items.length?branch(tree):'<div class="hint">没有匹配物品。试试清除搜索或筛选标签。</div>';root.scrollTop=scroll;
+ root.querySelectorAll('summary').forEach(summary=>summary.onclick=e=>{e.preventDefault();const key=summary.parentElement.dataset.path;if(treeOpen.has(key))treeOpen.delete(key);else treeOpen.add(key);renderTree()});'''.replace('\n+','\n')+s[b:]
a=s.index('function save(){');b=s.index('function mutate',a)
s=s[:a]+'''function currentFit(){return {...fitRecord,shipId:ship.id,slots:structuredClone(slots)}}
function save(){try{localStorage.setItem('fitlab-working-draft',JSON.stringify(currentFit()));$('#save').textContent='草稿已保留 · 待保存到装配库'}catch{$('#save').textContent='草稿存储失败，请保存装配'}scheduleAnalysis()}
'''+s[b:]
s=s.replace("function renderResources(){", "function renderResources(){if(report){const a=report.attributes;$('#resources').innerHTML=[['CPU',a.cpuUsed,a.cpuAvailable,'tf'],['能量栅格',a.powergridUsed,a.powergridAvailable,'MW']].map(([name,value,max,unit])=>`<div class=\"meter ${value>max?'over':''}\"><label>${name}<span>${value.toFixed(1)} / ${max} ${unit}</span></label><progress value=\"${Math.min(value,max)}\" max=\"${max||1}\"></progress></div>`).join('');return}")
s=s.replace("mountStats($('#ship-stats'),ship,slots,catalog,defenseEhp,", "mountStats($('#ship-stats'),ship,slots,catalog,defenseEhp,")
# backend renderer replaces display via separate module; preserve prototype when no result but explicitly pending
s=s.replace("function renderShipStats(){const scroll=", "function renderShipStats(){if(report){renderEngineStats();return}const scroll=")
s=s.replace("renderSlots();renderTree();renderResources();renderShipStats();\n", "renderSlots();renderTree();renderResources();renderShipStats();\n",1)
s += '''
async function api(path,body){const response=await fetch('/api/'+path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw Error(data.error||'请求失败');return data}
function updateShip(){ship=byId(fitRecord.shipId);for(const [kind,id] of Object.entries({high:14,mid:13,low:12,rig:1137}))counts[kind]=ship.attrs[id]||0;$('.title h1').textContent=fitRecord.name;$('#ship .ship-label').textContent=ship.en;$('#ship img').src=`https://images.evetech.net/types/${ship.id}/render?size=512`;$('#ship img').alt=ship.name;$('#ship .ship-caption').innerHTML=`${esc(ship.name)}<small>拖入弹药 · 装填全部兼容装备</small>`;$('#pilot').textContent=fitRecord.characterName||'选择角色技能';}
function restoreFit(record){analysisVersion++;report=null;fitRecord=structuredClone(record);updateShip();slots=fresh().map(s=>record.slots?.find(x=>x.key===s.key)||s);filter=null;history=[];$('#undo').disabled=true;$('#search').value='';treeOpen.clear();renderSlots();renderTree();renderResources();renderShipStats();save()}
async function persistFit(){const saved=await api('save',currentFit());fitRecord=saved;localStorage.setItem('fitlab-working-draft',JSON.stringify(currentFit()));$('#save').textContent='已保存 · '+new Date(saved.updatedAt).toLocaleTimeString();return saved}
function scheduleAnalysis(){report=null;analysisVersion++;clearTimeout(analysisTimer);$('#engine-status').textContent='计算中…';analysisTimer=setTimeout(runAnalysis,250)}
async function runAnalysis(){const version=analysisVersion;try{const result=await api('analyze',currentFit());if(version!==analysisVersion)return;report=result;$('#engine-status').textContent=`Dogma · ${result.skillCount} 项技能`;$('.notice').textContent=result.isValid?'装配校验通过':`校验提示：${result.issues.map(x=>x.message).join('；')}`;renderResources();renderShipStats()}catch(e){if(version!==analysisVersion)return;$('#engine-status').textContent='计算失败';$('.notice').textContent=e.message;say('装配已保留，计算失败：'+e.message)}}
const flow=document.createElement('dialog');flow.id='flow-dialog';document.body.append(flow);
function openFlow(title,body){flow.innerHTML=`<div class="flow-head"><b>${esc(title)}</b><button aria-label="关闭">×</button></div><div class="flow-body">${body}</div><p id="flow-error"></p>`;flow.querySelector('.flow-head button').onclick=()=>flow.close();flow.showModal()}
function guarded(fn){return async()=>{try{await fn()}catch(e){say(e.message);if(flow.open)$('#flow-error').textContent=e.message}}}
$('#save-fit').onclick=guarded(persistFit);
$('#fit-library').onclick=guarded(async()=>{await persistFit();const fits=await api('library');openFlow('装配库',`<input id="library-search" placeholder="搜索装配、舰船或标签"><div id="library-list"></div>`);const draw=()=>{const q=$('#library-search').value.toLowerCase();$('#library-list').innerHTML=fits.filter(f=>(f.name+' '+byId(f.shipId).name+' '+(f.tags||[]).join(' ')).toLowerCase().includes(q)).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).map(f=>`<button class="library-row" data-fit="${f.id}">${img(byId(f.shipId))}<span><b>${esc(f.name)}</b><small>${esc(byId(f.shipId).name)} · ${esc(f.characterName||'无技能')} · ${esc((f.tags||[]).join(' / '))}</small></span><span>打开 →</span></button>`).join('');flow.querySelectorAll('[data-fit]').forEach(b=>b.onclick=()=>{restoreFit(fits.find(f=>f.id===b.dataset.fit));flow.close()})};$('#library-search').oninput=draw;draw()});
$('#new-fit').onclick=guarded(async()=>{await persistFit();openFlow('新建装配 · 选择舰船',`<input id="hull-search" placeholder="搜索舰船名称、分类"><input id="fit-name" placeholder="装配名称（可选）"><div id="hull-list"></div>`);const draw=()=>{const q=$('#hull-search').value.toLowerCase(),hulls=catalog.filter(t=>t.kind==='ship'&&(t.name+' '+t.en+' '+t.path.join(' ')).toLowerCase().includes(q));const tree={};for(const t of hulls){let n=tree;for(const p of t.path){n[p]??={};n=n[p]}(n._items??=[]).push(t)}const branch=n=>Object.entries(n).map(([k,v])=>k==='_items'?v.map(t=>`<button class="library-row" data-hull="${t.id}" ${t.group===963?'disabled':''}>${img(t)}<span>${esc(t.name)}<small>${t.group===963?'子系统编辑尚未接入':esc(t.en)}</small></span></button>`).join(''):`<details ${q?'open':''}><summary>${esc(k)}</summary>${branch(v)}</details>`).join('');$('#hull-list').innerHTML=branch(tree);flow.querySelectorAll('[data-hull]').forEach(b=>b.onclick=()=>{const t=byId(b.dataset.hull),name=$('#fit-name').value.trim()||t.name+' · 新装配';restoreFit({name,shipId:t.id,skills:[],characterName:'无技能 · 基础对照',slots:[]});flow.close()})};$('#hull-search').oninput=draw;draw()});
$('#pilot').onclick=guarded(async()=>{const characters=await api('characters');openFlow('选择角色技能',`<p class="profile-note">应用技能快照到当前装配；不修改角色。未包含植入体和增效剂。</p><div id="character-list">${characters.map((c,i)=>`<button class="library-row" data-character="${i}"><span><b>${esc(c.name)}</b><small>${c.skills.length} 项技能 · ${esc(c.source)}</small></span><span>应用 →</span></button>`).join('')}</div><label class="import-skills">导入 ESI 技能 JSON<input type="file" id="skill-file" accept=".json"></label>`);flow.querySelectorAll('[data-character]').forEach(b=>b.onclick=()=>{const c=characters[Number(b.dataset.character)];fitRecord.skills=structuredClone(c.skills);fitRecord.characterName=c.name;updateShip();save();flow.close()});$('#skill-file').onchange=guarded(async()=>{const file=$('#skill-file').files[0],data=JSON.parse(await file.text()),rows=Array.isArray(data)?data:data.skills;if(!Array.isArray(rows))throw Error('JSON 中没有技能列表');const skills=rows.map(s=>({skillTypeId:s.skill_id??s.skillTypeId,level:s.active_skill_level??s.trained_skill_level??s.level}));const c=await api('character',{name:file.name.replace(/\\.json$/i,''),skills});fitRecord.skills=c.skills;fitRecord.characterName=c.name;updateShip();save();flow.close()})});
$('#rename-fit').onclick=()=>{openFlow('装配名称与标签',`<label>名称<input id="rename-value" value="${esc(fitRecord.name)}"></label><label>标签（逗号分隔）<input id="tags-value" value="${esc((fitRecord.tags||[]).join(', '))}"></label><button id="rename-save">保存</button>`);$('#rename-save').onclick=guarded(async()=>{const name=$('#rename-value').value.trim();if(!name)throw Error('名称不能为空');fitRecord.name=name;fitRecord.tags=$('#tags-value').value.split(/[,，]/).map(t=>t.trim()).filter(Boolean);updateShip();await persistFit();flow.close()})};
try{const draft=JSON.parse(localStorage.getItem('fitlab-working-draft'));if(draft&&byId(draft.shipId))restoreFit(draft);else{updateShip();scheduleAnalysis()}}catch{updateShip();scheduleAnalysis()}
'''
p.write_text(s,encoding='utf-8')
p=Path('index.html');s=p.read_text(encoding='utf-8');s=s.replace('<span class="prototype">交互原型 01</span>','<button id="fit-library">装配库</button><button id="new-fit">＋ 新建</button><button id="save-fit">保存装配</button>');s=s.replace('<span id="save">本机自动保存</span>','<div class="fit-actions"><button id="pilot">选择角色技能</button><button id="rename-fit">名称 / 标签</button><span id="save">草稿</span></div>');s=s.replace('<small>基础属性</small>','<small id="engine-status">连接计算服务…</small>');s=s.replace('SDE 3248221 · 本地控件实验室','SDE 3248221 · 装配工作台');p.write_text(s,encoding='utf-8')
