import {nativeAttributeDetail} from './native-attribute-detail.js';
import {scenarioDetail,deltaClass,metricText} from './scenario-display.js';
import {getLocale,translateFor} from './i18n.js';
import {attributeDetail,calculationDetail} from './engine-view.js?v=calculation-graphs-1';
const esc=t=>String(t??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const local=value=>typeof value==='string'?value:getLocale()==='zh-CN'?value?.zh||value?.en||'':getLocale()==='zh-TW'?translateFor('zh-TW',value?.zh||value?.en||''):value?.[getLocale()]||value?.en||value?.zh||'';
const number=n=>new Intl.NumberFormat(getLocale(),{maximumFractionDigits:4}).format(n);
const categoryNames={1:'装配',2:'护盾',3:'装甲',4:'结构',5:'电容',6:'锁定',7:'通用',8:'技能要求',9:'其他',10:'无人机',17:'速度与航行',20:'远程支援',21:'目标标记',22:'能量中和',23:'电子反制',24:'感应抑阻',25:'目标干扰',26:'跟踪扰断',27:'跃迁扰断',28:'停滞缠绕',29:'炮塔',30:'导弹',34:'铁骑舰载机能力',36:'电子战抗性',37:'加成',38:'铁骑舰载机属性',39:'超级武器',40:'机库与舱室',51:'采矿',52:'热量'};
const projected={cpuUsage:['装配','CPU 需求','tf'],powergridUsage:['装配','能量栅格需求','MW'],cycleTimeSeconds:['运行','周期','s'],reloadTimeSeconds:['运行','换弹时间','s'],magazineCapacity:['运行','弹夹容量','发'],chargeUnitsPerCycle:['运行','每周期弹药消耗','发'],capacitorUsagePerSecond:['运行','电容消耗','GJ/s'],damagePerSecond:['攻击','DPS',''],volleyDamage:['攻击','齐射伤害','HP'],optimalRangeMeters:['攻击','最佳射程','m'],falloffRangeMeters:['攻击','失准距离','m'],trackingSpeed:['攻击','跟踪速度',''],signatureResolutionMeters:['攻击','炮台分辨率','m'],missileExplosionRadiusMeters:['导弹','爆炸半径','m'],missileExplosionVelocityMetersPerSecond:['导弹','爆炸速度','m/s'],missileDamageReductionFactor:['导弹','伤害减免因子',''],missileDamageReductionSensitivity:['导弹','伤害减免敏感度',''],shieldRepairPerSecond:['防御','护盾修量','HP/s'],armorRepairPerSecond:['防御','装甲修量','HP/s'],structureRepairPerSecond:['防御','结构修量','HP/s'],capacitorTransferPerSecond:['支援','电容传输','GJ/s'],shieldHitpointsBonus:['防御','护盾量加成','HP'],armorHitpointsBonus:['防御','装甲量加成','HP'],structureHitpointsBonus:['防御','结构量加成','HP'],capacitorBonus:['电容','电容量加成','GJ'],speedBonus:['推进','速度加成','m/s'],turretDamageMultiplierBonus:['攻击','炮塔伤害倍率修正',''],damagePerSecondBonus:['弹药','伤害贡献 / 秒','HP/s'],volleyDamageBonus:['弹药','齐射伤害贡献','HP'],optimalRangeBonusMeters:['弹药','射程修正','m']};
const damageIcons={电磁:'<path d="m13 2-8 12h6l-1 8 9-13h-6Z"/>',热能:'<path d="M13 3c1 5 6 7 6 12a7 7 0 0 1-14 0c0-3 2-5 4-7 0 3 1 4 2 4 2-2 3-5 2-9Z"/>',动能:'<path d="m5 19 3-7 8-8 4 4-8 8-7 3Z M8 12l4 4 M3 12l3-3 M12 21l3-3"/>',爆炸:'<path d="m12 2 2 6 6-3-3 6 5 3-7 1 1 7-5-5-6 4 2-7-5-3 7-1Z"/>'};
const withUnit=(v,unit)=>unit==='m'&&v>1000?number(v/1000)+' km':number(v)+(unit?' '+unit:'');
const attrFields={cpuUsage:[50,'cpu',1],powergridUsage:[30,'power',1],cycleTimeSeconds:[51,'speed',1000],reloadTimeSeconds:[1795,'reloadTime',1000],optimalRangeMeters:[54,'maxRange',1],falloffRangeMeters:[158,'falloff',1],trackingSpeed:[160,'trackingSpeed',1],signatureResolutionMeters:[620,'signatureResolution',1],missileExplosionRadiusMeters:[654,'aoeCloudSize',1],missileExplosionVelocityMetersPerSecond:[653,'aoeVelocity',1]};
export function renderItemInfo(root,t,data,computed,catalog,context){
 const row=(label,value,help='',change=null)=>{const icon=damageIcons[label]?`<svg class="damage-icon" viewBox="0 0 24 24" aria-hidden="true">${damageIcons[label]}</svg>`:'';return `<div class="item-attribute" ${change?.detail?`tabindex="0" data-explain="${esc(JSON.stringify(change.detail))}"`:''}><dt>${icon}${esc(label)}</dt><dd class="${change?.direction||''}">${esc(value)}</dd></div>`};
 function changed(label,value,base,unit,attr,scale=1){
 const scenario=computed?.scenarioMetrics?.[attr];if(scenario)return {detail:scenarioDetail(label,metricText(scenario.value,unit),scenario.value,scenario.baseline,[],computed.scenarioMetrics.conditions),direction:deltaClass(scenario.value,scenario.baseline)};
 const path=attr?.split('.')||[],graph=path.reduce((n,k)=>n?.[k],computed?.calculationDetails);
 if((base==null||!Number.isFinite(base))&&!graph||base!=null&&Math.abs(value-base)<0.001)return null;
 if(graph){const detail=calculationDetail(graph,catalog,context);const improved=base!=null?value>base:null;return {detail,direction:improved===null?'':improved?'value-improved':'value-worsened'}}
const trace=computed?.attributeTraces?.[attr];const viewScale=unit==='m'&&value>1000?1000:1;let detail;
 if(trace?.isComplete&&Math.abs(trace.finalValue/scale-value)<0.001){detail=attributeDetail(label,value/viewScale,viewScale===1000?'km':unit,attr,{attributeTraces:computed.attributeTraces},catalog,context,scale*viewScale,'基础属性')}
 else if(computed?.state==='Offline')detail={title:label,result:withUnit(value,unit),terms:[['状态','离线'],['规则','不占用装配资源']],conditions:[]};
 else detail={title:label,result:withUnit(value,unit),terms:[['基础值',withUnit(base,unit)],['计算记录','缺少 '+(attr||label)+' 的组合公式或属性记录']],conditions:[['来源','引擎计算输出']]};
 const metadata=data.attributes.find(a=>a.name===attr);const highIsGood=metadata?.highIsGood??!['speed','duration','reloadTime','cpu','power','capacitorNeed'].includes(attr);const improved=highIsGood?value>base:value<base;return {direction:improved?'value-improved':'value-worsened',detail};}
 function format(a){let v=a.value,u=local(data.units[a.unitID]?.displayName);if(a.unitID===101){v/=1000;u='s'}if([108,111].includes(a.unitID)){v=(1-v)*100;u='%'}if(a.unitID===109){v=(v-1)*100;u='%'}if(a.unitID===127){v*=100;u='%'}if(a.unitID===117)return ({1:'小型',2:'中型',3:'大型',4:'旗舰级'})[v]||number(v);if(a.unitID===116)return catalog.find(t=>t.id===v)?.name||'未知物品';if(a.unitID===137)return v?'是':'否';if(a.unitID===104)return '× '+number(v);return withUnit(v,u)}
 const groups={};for(const a of data.attributes){if(!a.published||!local(a.displayName))continue;if(a.value===0&&a.displayWhenZero===false)continue;const group=categoryNames[a.attributeCategoryID]||'其他属性';(groups[group]??=[]).push(row(local(a.displayName),format(a),local(a.tooltipDescription)))}
 const sections=obj=>Object.entries(obj).map(([name,rows])=>`<section class="item-property-group"><h3>${esc(name)}</h3><dl>${rows.join('')}</dl></section>`).join('');
 const results={};const chargeType=computed?.charge?catalog.find(c=>c.id===computed.charge.dogmaTypeId):null;const baseCycle=computed?.nativeInspection?null:(t.attrs[51]||t.attrs[73]||0)/1000;const baseHit=computed?.nativeInspection?null:chargeType&&computed?.applicationKind==='Turret'?['114','118','117','116'].reduce((n,k)=>n+(chargeType.attrs[k]||0),0)*(t.attrs[64]||1):t.kind==='drone'?[114,118,117,116].reduce((n,k)=>n+(t.attrs[k]||0),0)*(t.attrs[64]||1):null;if(computed&&!computed.nativeInspection){computed={...computed};if(computed.charge){for(const [key,bonus] of [['damagePerSecond','damagePerSecondBonus'],['volleyDamage','volleyDamageBonus']])computed[key]=(computed[key]||0)+(computed.charge[bonus]||0);for(const [key,bonus] of [['damageProfilePerSecond','damageProfileBonus'],['volleyDamageProfile','volleyDamageProfileBonus']])computed[key]=Object.fromEntries(['em','thermal','kinetic','explosive'].map(k=>[k,(computed[key]?.[k]||0)+(computed.charge[bonus]?.[k]||0)]));}if(computed.scenarioMetrics){for(const key of ['damagePerSecond','volleyDamage'])computed[key]=computed.scenarioMetrics[key].value;computed.damageProfilePerSecond=computed.scenarioMetrics.profile;computed.volleyDamageProfile=null;}for(const [key,v] of Object.entries(computed)){if(typeof v!=='number'||!projected[key])continue;if(!v&&!computed.scenarioMetrics?.[key]&&!['cpuUsage','powergridUsage','cycleTimeSeconds'].includes(key))continue;const [group,baseLabel,unit]=projected[key];const label=key==='damagePerSecond'&&computed.scenarioMetrics?.attackMode==='edps'?'EDPS':baseLabel;if(group==='导弹'&&computed.applicationKind!=='Missile')continue;let mapping=attrFields[key];if(key==='cycleTimeSeconds'&&!t.attrs[51])mapping=[73,'duration',1000];const base=mapping?t.attrs[mapping[0]]/mapping[2]:key==='volleyDamage'?baseHit:key==='damagePerSecond'&&baseHit!=null&&baseCycle?baseHit/baseCycle:null;const change=changed(label,v,base,unit,mapping?.[1]||key,mapping?.[2]||1);(results[group]??=[]).push(row(label,withUnit(v,unit),'',change))}for(const [key,label] of [['damageProfilePerSecond','伤害 / 秒'],['volleyDamageProfile','齐射伤害'],['damageProfileBonus','弹药伤害 / 秒'],['volleyDamageProfileBonus','弹药齐射伤害']]){const profile=computed[key];if(profile&&Object.values(profile).some(v=>v>0))(results[label]??=[]).push(...['em','thermal','kinetic','explosive'].map((k,i)=>row(['电磁','热能','动能','爆炸'][i],number(profile[k]||0),'',(()=>{const base=chargeType&&computed.applicationKind==='Turret'?(chargeType.attrs[[114,118,117,116][i]]||0)*(t.attrs[64]||1)/(key==='damageProfilePerSecond'?baseCycle:1):null;return changed(['电磁','热能','动能','爆炸'][i],profile[k]||0,base,'',key+'.'+k)})())))}}
 if(computed?.nativeInspection){
  const inspection=computed.nativeInspection;
  for(const reading of inspection.items){
   const a=data.attributes.find(a=>a.id===reading.query.attributeId);if(!a)continue;
   const label=local(a.displayName)||a.name,view=nativeAttributeDetail(reading,inspection,label,value=>format({...a,value}),catalog);
   (results[categoryNames[a.attributeCategoryID]||'其他属性']??=[]).push(row(label,view.value,'',view));
  }
 }
 if(computed?.scenarioMetrics){for(const key of ['damagePerSecond','volleyDamage'])if(computed.scenarioMetrics[key].value===null)(results['攻击']??=[]).push(row(projected[key][1],'—（应用模型未支持）'));}
 if(computed?.attributeSnapshot){
  const already=new Set(t.kind==='ship'?[]:['speed','duration','maxRange','falloff','trackingSpeed','signatureResolution','emDamage','thermalDamage','kineticDamage','explosiveDamage']);
  for(const a of data.attributes){
   const value=computed.attributeSnapshot[a.name]??computed.attributeTraces?.[a.name]?.finalValue;
   if(!a.published||!local(a.displayName)||already.has(a.name)||!Number.isFinite(value)||t.kind==='ship'&&a.name==='baseWarpSpeed'&&!Number.isFinite(computed.attributeSnapshot.baseWarpSpeed))continue;
   const unit=local(data.units[a.unitID]?.displayName),change=changed(local(a.displayName),value,a.value,unit,a.name);
   (results[categoryNames[a.attributeCategoryID]||'无人机属性']??=[]).push(row(local(a.displayName),format({...a,value}),'',change));
  }
 }
 const effects=data.effects.filter(e=>e._key).map(e=>`<details class="item-effect"><summary>${esc(local(e.displayName)||e.name)}<small>${esc({0:'被动',1:'启用',2:'目标',3:'范围',4:'在线',5:'超载',6:'环境',7:'系统'}[e.effectCategoryID]||'其他')}</small></summary><div>${local(e.description)?`<p>${esc(local(e.description))}</p>`:''}${(e.modifierInfo||[]).map(m=>{const target=data.attributes.find(a=>a._key===m.modifiedAttributeID);return row(local(target?.displayName)||'属性修正',{'-1':'前置赋值',0:'前置乘法',1:'前置除法',2:'加法',3:'减法',4:'后置乘法',5:'后置除法',6:'百分比',7:'后置赋值'}[m.operation]||'特殊效果')}).join('')||'<p class="profile-note">此效果的行为由引擎规则处理。</p>'}</div></details>`).join('');
 const rawDescription=new DOMParser().parseFromString(local(data.description).replace(/<br\s*\/?>/gi,'\n'),'text/html').body.textContent;
 const description=t.kind==='loadout'?rawDescription.replace(/\n[ \t\r]*\n(?:[ \t\r]*\n)+/g,'\n\n'):rawDescription;
 root.innerHTML=`<div class="info-identity"><img src="https://images.evetech.net/types/${t.id}/icon?size=64" alt=""><div><h2>${esc(t.name)}</h2><small>${esc(t.en)}</small></div></div>${description?.trim()?`<p class="info-description">${esc(description.trim())}</p>`:''}<nav class="info-tabs">${computed?'<button data-info-tab="computed">装配参数</button>':''}<button data-info-tab="base">基础属性</button><button data-info-tab="effects">效果定义</button></nav>${computed?`<div data-info-pane="computed"><p class="profile-note">${esc(context)} · 查看时的引擎计算快照</p>${computed?.nativeInspection&&!computed.nativeInspection.staticCoverageComplete?'<p class="profile-note">部分属性受未支持效果影响，已逐项标记。</p>':''}${computed?.nativeInspection?.errors.length?'<p class="profile-note">装配存在校验问题；以下为可读取的诊断属性，不代表装配已合法。</p>':''}${sections(results)||'<p>引擎未返回此物品的独立参数。</p>'}</div>`:''}<div data-info-pane="base"><p class="profile-note">SDE ${esc(data.source?.buildNumber??"未声明版本")} 基础值 · 未计入技能与装备修正</p>${sections(groups)}</div><div data-info-pane="effects"><p class="profile-note">SDE 效果定义 · 不代表本次装配的执行日志</p>${effects||'<p>没有效果定义。</p>'}</div>`;
 const choose=tab=>{root.querySelectorAll('[data-info-pane]').forEach(p=>p.hidden=p.dataset.infoPane!==tab);root.querySelectorAll('[data-info-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.infoTab===tab)))};root.querySelectorAll('[data-info-tab]').forEach(b=>b.onclick=()=>choose(b.dataset.infoTab));choose(computed?'computed':'base');
}
