from pathlib import Path
p=Path('item-info.js');s=p.read_text(encoding='utf-8');s="import {attributeDetail} from './engine-view.js';\n"+s
pos=s.index('export function renderItemInfo');s=s[:pos]+'''const damageIcons={电磁:'<path d="m13 2-8 12h6l-1 8 9-13h-6Z"/>',热能:'<path d="M13 3c1 5 6 7 6 12a7 7 0 0 1-14 0c0-3 2-5 4-7 0 3 1 4 2 4 2-2 3-5 2-9Z"/>',动能:'<path d="m5 19 3-7 8-8 4 4-8 8-7 3Z M8 12l4 4 M3 12l3-3 M12 21l3-3"/>',爆炸:'<path d="m12 2 2 6 6-3-3 6 5 3-7 1 1 7-5-5-6 4 2-7-5-3 7-1Z"/>'};
const withUnit=(v,unit)=>unit==='m'&&v>1000?number(v/1000)+' km':number(v)+(unit?' '+unit:'');
const attrFields={cpuUsage:[50,'cpu',1],powergridUsage:[30,'power',1],cycleTimeSeconds:[51,'speed',1000],reloadTimeSeconds:[1795,'reloadTime',1000],optimalRangeMeters:[54,'maxRange',1],falloffRangeMeters:[158,'falloff',1],trackingSpeed:[160,'trackingSpeed',1],signatureResolutionMeters:[620,'signatureResolution',1],missileExplosionRadiusMeters:[654,'aoeCloudSize',1],missileExplosionVelocityMetersPerSecond:[653,'aoeVelocity',1]};
'''+s[pos:]
a=s.index(' const row=');b=s.index(' function format',a)
s=s[:a]+''' const row=(label,value,help='',change=null)=>{const icon=damageIcons[label]?`<svg class="damage-icon" viewBox="0 0 24 24" aria-hidden="true">${damageIcons[label]}</svg>`:'';return `<div class="item-attribute" ${change?.detail?`tabindex="0" data-explain="${esc(JSON.stringify(change.detail))}"`:''}><dt>${icon}${esc(label)}</dt><dd class="${change?.direction||''}">${esc(value)}</dd></div>`};
 function changed(label,value,base,unit,attr,scale=1){if(base==null||!Number.isFinite(base)||Math.abs(value-base)<0.001)return null;const trace=computed?.attributeTraces?.[attr];const viewScale=unit==='m'&&value>1000?1000:1;let detail;
 if(trace?.isComplete&&Math.abs(trace.finalValue/scale-value)<0.001){detail=attributeDetail(label,value/viewScale,viewScale===1000?'km':unit,attr,{attributeTraces:computed.attributeTraces},catalog,context,scale*viewScale,'基础属性')}
 else detail={title:label,result:withUnit(value,unit),terms:[['基础值',withUnit(base,unit)],['计算记录',computed?.state==='Offline'?'离线状态：资源不占用':'此组合值尚无完整逐项记录']],conditions:[['来源','引擎计算输出']]};
 return {direction:value>base?'value-increased':'value-decreased',detail};}
'''+s[b:]
s=s.replace("return `${number(v)}${u?' '+u:''}`", "return withUnit(v,u)")
s=s.replace("const results={};if(computed){computed={...computed};", "const results={};const chargeType=computed?.charge?catalog.find(c=>c.id===computed.charge.dogmaTypeId):null;const baseCycle=(t.attrs[51]||t.attrs[73]||0)/1000;const baseHit=chargeType&&computed?.applicationKind==='Turret'?['114','118','117','116'].reduce((n,k)=>n+(chargeType.attrs[k]||0),0)*(t.attrs[64]||1):null;if(computed){computed={...computed};")
s=s.replace("(results[group]??=[]).push(row(label,number(v)+(unit?' '+unit:'')))", "let mapping=attrFields[key];if(key==='cycleTimeSeconds'&&!t.attrs[51])mapping=[73,'duration',1000];const base=mapping?t.attrs[mapping[0]]/mapping[2]:key==='volleyDamage'?baseHit:key==='damagePerSecond'&&baseHit!=null&&baseCycle?baseHit/baseCycle:null;const change=changed(label,v,base,unit,mapping?.[1],mapping?.[2]||1);(results[group]??=[]).push(row(label,withUnit(v,unit),'',change))")
s=s.replace("row(['电磁','热能','动能','爆炸'][i],number(profile[k]||0))", "row(['电磁','热能','动能','爆炸'][i],number(profile[k]||0),'',(()=>{const base=chargeType&&computed.applicationKind==='Turret'?(chargeType.attrs[[114,118,117,116][i]]||0)*(t.attrs[64]||1)/(key==='damageProfilePerSecond'?baseCycle:1):null;return changed(['电磁','热能','动能','爆炸'][i],profile[k]||0,base,'',null)})())")
p.write_text(s,encoding='utf-8')
p=Path('explanations.js');s=p.read_text(encoding='utf-8');s=s.replace("new MutationObserver(()=>{const i=chain.findIndex(n=>!n.anchor.isConnected);if(i>=0)closeFrom(i)}).observe(document.querySelector('.inspector'),{childList:true,subtree:true});", "const observer=new MutationObserver(()=>{const i=chain.findIndex(n=>!n.anchor.isConnected||n.anchor.closest('[hidden]'));if(i>=0)closeFrom(i)});for(const root of document.querySelectorAll('.inspector,#info-window'))observer.observe(root,{childList:true,subtree:true,attributes:true,attributeFilter:['hidden']});")
p.write_text(s,encoding='utf-8')
