import {createSkillPointDisplay,skillPointNote} from './skill-points.js';
import {readPilotFolders,writePilotFolders,onPilotFoldersChanged} from './pilot-folders.js';

export function installPilotPicker(anchor,{api,select,current,catalog}){
 const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const pointText=createSkillPointDisplay(catalog);
 let prefs=readPilotFolders();
 const panel=document.createElement('section');panel.id='pilot-picker';panel.hidden=true;panel.role='dialog';panel.setAttribute('aria-label','选择驾驶员');
 panel.innerHTML='<div class="pilot-picker-tools"><input aria-label="搜索驾驶员" placeholder="搜索角色或文件夹"><button class="new-folder" title="新建文件夹" aria-label="新建角色文件夹">＋ 文件夹</button></div><div class="pilot-folder-editor" hidden></div><div class="pilot-tree"></div><div class="pilot-picker-footer"><span>拖入文件夹 · 右键管理</span></div><div class="pilot-picker-error" role="status"></div><div class="pilot-picker-menu" role="menu" hidden></div>';
 document.body.append(panel);
 const tree=panel.querySelector('.pilot-tree'),search=panel.querySelector('.pilot-picker-tools input'),menu=panel.querySelector('.pilot-picker-menu'),editor=panel.querySelector('.pilot-folder-editor'),error=panel.querySelector('.pilot-picker-error');
 let characters=[],generation=0,dragged=null;
 const save=()=>{try{writePilotFolders(prefs)}catch{error.textContent='文件夹保存失败'}};
 const position=()=>{if(panel.hidden)return;const r=anchor.getBoundingClientRect();panel.style.width=Math.min(350,innerWidth-16)+'px';panel.style.left=Math.max(8,Math.min(r.right-panel.offsetWidth,innerWidth-panel.offsetWidth-8))+'px';panel.style.top=Math.min(r.bottom+7,innerHeight-160)+'px';panel.style.maxHeight=Math.max(120,innerHeight-parseFloat(panel.style.top)-8)+'px'};
 const close=()=>{panel.hidden=true;menu.hidden=true;editor.hidden=true;anchor.setAttribute('aria-expanded','false');generation++};
 const folderOf=c=>prefs.folders.some(f=>f.id===prefs.assignment[String(c.id)])?prefs.assignment[String(c.id)]:'';
 const move=(id,folder)=>{prefs.assignment[String(id)]=folder;save();draw()};
 const folderEditor=(folder=null)=>{menu.hidden=true;editor.hidden=false;editor.innerHTML='<input aria-label="文件夹名称" maxlength="40" placeholder="文件夹名称"><button>确定</button>';const input=editor.querySelector('input');input.value=folder?.name||'';input.focus();const commit=()=>{const name=input.value.trim();if(!name)return;if(folder)folder.name=name;else prefs.folders.push({id:crypto.randomUUID(),name,open:true});save();editor.hidden=true;draw()};editor.querySelector('button').onclick=commit;input.onkeydown=e=>{if(e.isComposing)return;if(e.key==='Enter')commit();if(e.key==='Escape'){e.stopPropagation();editor.hidden=true;search.focus()}}};
 const context=(e,entries)=>{e.preventDefault();menu.innerHTML='';for(const [label,fn] of entries){const b=document.createElement('button');b.role='menuitem';b.textContent=label;b.onclick=()=>{menu.hidden=true;fn()};menu.append(b)}menu.hidden=false;const r=panel.getBoundingClientRect();menu.style.left=Math.max(4,Math.min(e.clientX-r.left,panel.clientWidth-menu.offsetWidth-4))+'px';menu.style.top=Math.max(4,Math.min(e.clientY-r.top,panel.clientHeight-menu.offsetHeight-4))+'px';menu.querySelector('button')?.focus()};
 function draw(){
  const q=search.value.trim().toLowerCase();
  const row=c=>'<button class="pilot-tree-person" draggable="true" data-person="'+esc(c.id)+'" aria-label="'+esc(c.name)+'" aria-current="'+(current()===c.name)+'"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" aria-hidden="true"><circle cx="12" cy="7" r="4"/><path d="M4 22v-3a8 8 0 0 1 16 0v3"/></svg><span>'+esc(c.name.replace(' · 模拟角色',''))+'<small>'+c.skills.length+' 项技能 · '+esc(c.source)+'</small><small class="pilot-person-sp" title="'+skillPointNote+'">'+pointText(c)+' SP</small></span>'+(current()===c.name?'<b>✓</b>':'')+'</button>';
  tree.innerHTML=prefs.folders.map(f=>{const rows=characters.filter(c=>folderOf(c)===f.id&&(f.name.toLowerCase().includes(q)||c.name.toLowerCase().includes(q)));if(q&&!rows.length&&!f.name.toLowerCase().includes(q))return '';return '<details data-folder="'+f.id+'" '+((q||f.open!==false)?'open':'')+'><summary><svg class="pilot-folder-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" aria-hidden="true"><path d="M3 6h7l2 3h9v12H3Z"/></svg>'+esc(f.name)+'<small>'+rows.length+'</small></summary>'+rows.map(row).join('')+(!rows.length?'<div class="pilot-empty">拖入角色</div>':'')+'</details>'}).join('')+'<div class="pilot-root" data-folder="">'+characters.filter(c=>!folderOf(c)&&c.name.toLowerCase().includes(q)).map(row).join('')+'</div>';
  if(!tree.querySelector('.pilot-tree-person,details'))tree.innerHTML='<div class="pilot-empty">没有匹配角色</div>';
  tree.querySelectorAll('[data-person]').forEach(b=>{const c=characters.find(c=>String(c.id)===b.dataset.person);b.onclick=()=>{select(c);close();anchor.focus()};b.ondragstart=e=>{dragged=c.id;e.dataTransfer.setData('text/plain',String(c.id));e.dataTransfer.effectAllowed='move'};b.ondragend=()=>{dragged=null;tree.querySelectorAll('.drop-target').forEach(e=>e.classList.remove('drop-target'))};b.oncontextmenu=e=>context(e,[['移到根目录',()=>move(c.id,'')],...prefs.folders.map(f=>['移到 '+f.name,()=>move(c.id,f.id)])])});
  tree.querySelectorAll('[data-folder]').forEach(el=>{el.ondragover=e=>{if(dragged===null)return;e.preventDefault();e.stopPropagation();e.dataTransfer.dropEffect='move';el.classList.add('drop-target')};el.ondragleave=()=>el.classList.remove('drop-target');el.ondrop=e=>{if(dragged===null)return;e.preventDefault();e.stopPropagation();move(dragged,el.dataset.folder);dragged=null};if(el.tagName==='DETAILS'){const f=prefs.folders.find(f=>f.id===el.dataset.folder);el.ontoggle=()=>{if(el.isConnected&&!search.value&&f.open!==el.open){f.open=el.open;save()}};el.querySelector('summary').oncontextmenu=e=>context(e,[['重命名文件夹',()=>folderEditor(f)],['删除文件夹（角色移回根目录）',()=>{prefs.folders=prefs.folders.filter(x=>x.id!==f.id);save();draw()}]])}});
 }
 onPilotFoldersChanged(()=>{prefs=readPilotFolders();if(!panel.hidden)draw()});
 anchor.onclick=async()=>{prefs=readPilotFolders();if(!panel.hidden){close();return}panel.hidden=false;anchor.setAttribute('aria-expanded','true');position();search.focus();error.textContent='';const token=++generation;tree.textContent='正在读取驾驶员…';try{const result=await api('characters');if(token!==generation)return;characters=result;draw()}catch(e){if(token===generation)error.textContent=e.message}};
 anchor.setAttribute('aria-expanded','false');anchor.setAttribute('aria-controls',panel.id);
 search.oninput=draw;panel.querySelector('.new-folder').onclick=()=>folderEditor();
 panel.addEventListener('pointerdown',e=>{if(!e.target.closest('.pilot-picker-menu'))menu.hidden=true});
 panel.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();if(!menu.hidden)menu.hidden=true;else{close();anchor.focus()}}});
 document.addEventListener('pointerdown',e=>{if(!panel.contains(e.target)&&!anchor.contains(e.target))close()});
 window.addEventListener('resize',position);window.addEventListener('scroll',position,true);window.addEventListener('hashchange',close);
}
