const words={
 'zh-CN':{title:'战斗沙盒 · 预览',intro:'当前仅为概念演示。正式版本将采用 3D 空间作战，UI 也会重新设计。',back:'返回装配',replay:'引擎战斗回放',view:'重置视角',help:'拖动平移 · 滚轮缩放 · 点击舰船查看',blue:'蓝方',red:'红方',fleet:'参战舰队',scope:'凤凰遭小队围攻 · 六舰近距对照。使用原实验已支持的配置；会战、资本盾修等未支持模块未计入。二维插值仅作展示。',play:'播放',pause:'暂停',restart:'重播',script:'查看脚本', 'script-note':'每阵营一个策略 · 只读预览',loading:'正在读取战斗记录…',failed:'战斗记录读取失败，请刷新重试。',shield:'护盾',armor:'装甲',hull:'结构',capacitor:'电容',sample:'状态每 5 秒采样 · 动作按事件时间回放',gun:'炮击',laser:'激光',missile:'导弹',web:'电子战',rifter:'裂谷级',caracal:'狞獾级',ended:'回放结束'},
 en:{title:'Battle sandbox · Preview',intro:'Concept demo only. The full version will feature 3D space combat and a redesigned UI.',back:'Back to fitting',replay:'Engine battle replay',view:'Reset view',help:'Drag to pan · Scroll to zoom · Select a ship',blue:'Blue',red:'Red',fleet:'FLEET',scope:'Phoenix under squad assault: six-ship near-range control. Unsupported siege and capital shield repair modules are omitted. Interpolated 2D replay.',play:'Play',pause:'Pause',restart:'Replay',script:'View script','script-note':'One policy per team · Read-only preview',loading:'Loading battle recording…',failed:'Could not load recording. Refresh to retry.',shield:'Shield',armor:'Armor',hull:'Hull',capacitor:'Capacitor',sample:'State sampled every 5 seconds; actions use event times',gun:'Turrets',laser:'Lasers',missile:'Missiles',web:'Electronic warfare',rifter:'Rifter',caracal:'Caracal',ended:'Replay complete'},
 'zh-TW':{title:'戰鬥沙盒 · 預覽',intro:'目前僅為概念展示。正式版本將採用 3D 空間作戰，UI 也會重新設計。',back:'返回裝配',replay:'引擎戰鬥回放',view:'重設視角',help:'拖動平移 · 滾輪縮放 · 點擊艦船查看',blue:'藍方',red:'紅方',fleet:'參戰艦隊',scope:'鳳凰遭小隊圍攻 · 六艦近距對照。未計入尚未支援的會戰與資本盾修模組；二維插值僅供展示。',play:'播放',pause:'暫停',restart:'重播',script:'查看腳本','script-note':'每陣營一個策略 · 唯讀預覽',loading:'正在讀取戰鬥記錄…',failed:'記錄讀取失敗，請重新整理。',shield:'護盾',armor:'裝甲',hull:'結構',capacitor:'電容',sample:'狀態每 5 秒取樣 · 動作依事件時間回放',gun:'炮擊',laser:'雷射',missile:'飛彈',web:'電子戰',rifter:'裂谷級',caracal:'獰獾級',ended:'回放結束'},
 ja:{title:'戦闘サンドボックス · プレビュー',intro:'現在はコンセプトデモです。正式版では3D空間での戦闘を実装し、UIも再設計します。',back:'装備画面へ',replay:'エンジン戦闘リプレイ',view:'視点をリセット',help:'ドラッグで移動 · ホイールで拡大 · 艦船を選択',blue:'青チーム',red:'赤チーム',fleet:'艦隊',scope:'フェニックス対6隻の近距離実験。未対応のシージやキャピタルシールド修復を除外した構成。2D補間リプレイです。',play:'再生',pause:'一時停止',restart:'最初から',script:'スクリプト','script-note':'チームごとの戦略 · 読み取り専用',loading:'戦闘記録を読み込み中…',failed:'記録を読み込めません。再読み込みしてください。',shield:'シールド',armor:'アーマー',hull:'ストラクチャ',capacitor:'キャパシタ',sample:'状態は5秒ごとの記録、演出はイベント時刻に同期',gun:'タレット',laser:'レーザー',missile:'ミサイル',web:'電子戦',rifter:'リフター',caracal:'カラカル',ended:'再生終了'}
};
const lang=new URLSearchParams(location.search).get('lang')||'zh-CN',dict=words[lang]||words.en,t=key=>dict[key]||words.en[key]||key;
document.documentElement.lang=words[lang]?lang:'en';document.querySelectorAll('[data-text]').forEach(e=>e.textContent=t(e.dataset.text));
document.querySelector('#scene-name').textContent=({'zh-CN':'凤凰遭小队围攻 · 六舰近距对照','zh-TW':'鳳凰遭小隊圍攻 · 六艦近距對照',ja:'フェニックスへの集中攻撃 · 6隻の近距離実験'})[lang]||'Phoenix under assault · Six-ship near-range control';
const $=s=>document.querySelector(s),canvas=$('#battle'),ctx=canvas.getContext('2d');
let data,time=0,playing=false,selected='blue-gun',zoom=1,pan={x:0,y:0},width=1,height=1,last=0,uiLast=-1,raf,drag=null;
const images=new Map(),color=id=>data?.ships.find(s=>s.id===id)?.team==='blue'?'#78d2ed':'#f28e85';
let bounds={x:0,y:0,w:11000,h:10000};
const role=id=>id.endsWith('gun')?'gun':id.endsWith('laser')?'laser':id.endsWith('missile')?'missile':'web';
const name=s=>s.names?.[lang]||s.names?.en||s.id;
const scale=()=>Math.min((width-140)/bounds.w,(height-170)/bounds.h)*zoom;
const project=p=>({x:width/2+(p.x-bounds.x)*scale()+pan.x,y:height/2-(p.y-bounds.y)*scale()+pan.y});
const state=()=>data.frames[Math.min(Math.floor(time/(data.sampleSeconds||1)),data.frames.length-1)];
function position(id){const a=state().ships.find(s=>s.id===id),b=data.frames[Math.min(Math.floor(time/(data.sampleSeconds||1))+1,data.frames.length-1)].ships.find(s=>s.id===id),f=(time-state().time)/(data.sampleSeconds||1);return project({x:a.position.x+(b.position.x-a.position.x)*f,y:a.position.y+(b.position.y-a.position.y)*f});}
function setPlaying(value){playing=value;$('#play').textContent=t(value?'pause':'play');}
function updateInfo(){
 const frame=state(),s=frame.ships.find(s=>s.id===selected),meta=data.ships.find(s=>s.id===selected);
 $('#inspect').replaceChildren();const title=document.createElement('h2');title.textContent=name(meta);$('#inspect').append(title);
 for(const layer of [...s.layers,{name:'capacitor',hitpoints:s.capacitor,capacity:s.capacitorCapacity}]){const row=document.createElement('div');row.className='meter';const label=document.createElement('label'),value=document.createElement('span');label.textContent=t(layer.name);value.textContent=Math.round(layer.hitpoints).toLocaleString(lang)+' / '+Math.round(layer.capacity).toLocaleString(lang);label.append(value);const bar=document.createElement('progress');bar.max=layer.capacity;bar.value=layer.hitpoints;row.append(label,bar);$('#inspect').append(row);}
 const note=document.createElement('small');note.className='note';note.textContent=t('sample');$('#inspect').append(note);
 $('#roster').querySelectorAll('button').forEach(e=>e.setAttribute('aria-pressed',String(e.dataset.id===selected)));
 const clock=n=>Math.floor(n/60).toString().padStart(2,'0')+':'+(n%60).toFixed(1).padStart(4,'0');$('#clock').textContent=clock(time)+' / '+clock(data.duration);$('#seek').value=time;
 const recent=data.events.filter(e=>e.timeUs<=time*1e6&&['MissileLaunched','MissileImpacted','EffectStarted','EnergyResolved','LockCompleted'].includes(e.kind)).slice(-4);$('#battle-activity').replaceChildren();
 const kinds=lang==='zh-CN'?{MissileLaunched:'发射导弹',MissileImpacted:'导弹命中',EffectStarted:'效果生效',EnergyResolved:'能量作用',LockCompleted:'完成锁定'}:lang==='zh-TW'?{MissileLaunched:'發射飛彈',MissileImpacted:'飛彈命中',EffectStarted:'效果生效',EnergyResolved:'能量作用',LockCompleted:'完成鎖定'}:{};
 for(const e of recent){const line=document.createElement('div'),source=data.ships.find(s=>s.id===e.sourceId),target=data.ships.find(s=>s.id===e.targetId);line.textContent=(e.timeUs/1e6).toFixed(1)+'s · '+(source?name(source):e.sourceId||'')+' → '+(target?name(target):e.targetId||'')+' · '+(kinds[e.kind]||e.kind);$('#battle-activity').append(line);}

}
function stroke(a,b,c,alpha=1,lineWidth=1){ctx.globalAlpha=alpha;ctx.strokeStyle=c;ctx.lineWidth=lineWidth;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.globalAlpha=1;}
function draw(){
 ctx.clearRect(0,0,width,height);const cell=Math.max(20,1000*scale());ctx.lineWidth=1;ctx.strokeStyle='#63879a15';for(let x=(width/2+pan.x)%cell;x<width;x+=cell){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,height);ctx.stroke();}for(let y=(height/2+pan.y)%cell;y<height;y+=cell){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(width,y);ctx.stroke();}
 if(!data)return;
 for(const effect of data.effects){if(time*1e6<effect.startedAtUs||time*1e6>=Math.min(effect.expiresAtUs,effect.endedAtUs??Infinity))continue;const a=position(effect.sourceId),b=position(effect.targetId),c=effect.channel==='MaxSpeed'?'#b694ef':['LockRange','ScanResolution'].includes(effect.channel)?'#6ebdbe':'#efb16c';ctx.setLineDash([4,7]);ctx.lineDashOffset=-time*20;stroke(a,b,c,.4,1.5);ctx.setLineDash([]);const f=(time*1.4)%1;ctx.strokeStyle=c;ctx.globalAlpha=(1-f)*.6;ctx.beginPath();ctx.arc(b.x,b.y,24+f*24,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1;}
 for(const e of data.events){const age=time-e.timeUs/1e6;if(age<0||age>0.6)continue;
  if(e.kind==='TurretResolved'){const a=position(e.sourceId),b=position(e.targetId),laser=role(e.sourceId)==='laser';if(laser){stroke(a,b,'#fb887f',Math.max(0,1-age/.5),3);stroke(a,b,'#ffe3ad',Math.max(0,1-age/.4),1);}else{const f=Math.min(1,age/.18),q={x:a.x+(b.x-a.x)*f,y:a.y+(b.y-a.y)*f};stroke({x:q.x-(b.x-a.x)*.07,y:q.y-(b.y-a.y)*.07},q,'#ffe3a1',1-age/.6,2);}}
  if(e.kind==='EnergyResolved'&&e.sourceId&&e.targetId){stroke(position(e.sourceId),position(e.targetId),'#dc81ee',1-age/.6,3);}
  if(['RepairApplied','RepairResolved'].includes(e.kind)&&e.sourceId&&e.targetId){stroke(position(e.sourceId),position(e.targetId),'#7ae4a5',1-age/.6,3);}
  if(e.kind==='MissileImpacted'){const q=position(e.targetId);ctx.globalAlpha=1-age/.6;ctx.fillStyle='#ffd997';ctx.beginPath();ctx.arc(q.x,q.y,4+age*30,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;}
 }
 for(const m of data.missiles){const end=m.endUs??m.expiresAtUs,start=m.launchedAtUs;if(time*1e6<start||time*1e6>=end)continue;const a=project(m.launchPosition),b=position(m.targetId),f=(time*1e6-start)/(end-start),offset=(Number(m.id.split('-')[1])%5-2)*3,q={x:a.x+(b.x-a.x)*f,y:a.y+(b.y-a.y)*f+offset};stroke({x:q.x-(b.x-a.x)*.09,y:q.y-(b.y-a.y)*.09},q,'#ffc274',.7,2);ctx.fillStyle='#fff0c7';ctx.beginPath();ctx.arc(q.x,q.y,2,0,Math.PI*2);ctx.fill();}
 const labelBoxes=[];
 for(const meta of data.ships){const trail=data.frames.filter(f=>f.time<=time&&f.time>=time-40).map(f=>project(f.ships.find(s=>s.id===meta.id).position));ctx.strokeStyle=color(meta.id);ctx.globalAlpha=.2;ctx.lineWidth=1;ctx.beginPath();trail.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();ctx.globalAlpha=1;}
 for(const meta of data.ships){const s=state().ships.find(s=>s.id===meta.id),q=position(meta.id),image=images.get(meta.typeId);ctx.globalAlpha=s.destroyed?.3:1;ctx.strokeStyle=color(meta.id);ctx.lineWidth=selected===meta.id?2:1;ctx.beginPath();ctx.arc(q.x,q.y,25,0,Math.PI*2);ctx.stroke();if(selected===meta.id){ctx.strokeStyle='#dcecfb35';ctx.beginPath();ctx.arc(q.x,q.y,32,0,Math.PI*2);ctx.stroke();}if(image?.complete&&image.naturalWidth)ctx.drawImage(image,q.x-20,q.y-20,40,40);else{ctx.fillStyle=color(meta.id);ctx.fillRect(q.x-8,q.y-8,16,16);}ctx.font='11px Segoe UI';ctx.textAlign='center';ctx.fillStyle=color(meta.id);const text=name(meta),tw=ctx.measureText(text).width;let ly=q.y+44;while(labelBoxes.some(r=>Math.abs(r.x-q.x)<(r.w+tw)/2+6&&Math.abs(r.y-ly)<15))ly+=16;labelBoxes.push({x:q.x,y:ly,w:tw});ctx.fillText(text,q.x,ly);s.layers.forEach((l,i)=>{ctx.fillStyle='#263949';ctx.fillRect(q.x-21,q.y+28+i*3,42,2);ctx.fillStyle=['#86cfe6','#c2bba0','#b18f87'][i];ctx.fillRect(q.x-21,q.y+28+i*3,42*l.hitpoints/l.capacity,2);});ctx.globalAlpha=1;}
}
function tick(now){if(last&&playing&&!document.hidden){time=Math.min(data.duration,time+(now-last)/1000*Number($('#speed').value));if(time>=data.duration)setPlaying(false);}last=now;draw();if(data&&Math.abs(time-uiLast)>.1){updateInfo();uiLast=time;}raf=requestAnimationFrame(tick);}
new ResizeObserver(()=>{const r=canvas.getBoundingClientRect(),dpr=devicePixelRatio||1;width=r.width;height=r.height;canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);draw();}).observe(canvas);
canvas.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.4,Math.min(4,zoom*Math.exp(-e.deltaY*.001)));},{passive:false});
canvas.onpointerdown=e=>{drag={x:e.clientX,y:e.clientY,px:pan.x,py:pan.y};canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(drag)pan={x:drag.px+e.clientX-drag.x,y:drag.py+e.clientY-drag.y};};canvas.onpointerup=e=>{if(drag&&Math.hypot(e.clientX-drag.x,e.clientY-drag.y)<5&&data){const r=canvas.getBoundingClientRect(),hit=data.ships.find(s=>{const q=position(s.id);return Math.hypot(q.x-(e.clientX-r.left),q.y-(e.clientY-r.top))<28;});if(hit){selected=hit.id;updateInfo();}}drag=null;};canvas.onpointercancel=()=>drag=null;
$('#reset-view').onclick=()=>{zoom=1;pan={x:0,y:0};};$('#play').onclick=()=>{if(time>=data.duration)time=0;setPlaying(!playing);};$('#restart').onclick=()=>{time=0;uiLast=-1;setPlaying(true);};$('#seek').oninput=e=>{time=Number(e.target.value);uiLast=-1;updateInfo();};$('#script-toggle').onclick=()=>{$('#script-panel').hidden=!$('#script-panel').hidden;$('#script-toggle').setAttribute('aria-expanded',String(!$('#script-panel').hidden));};$('#close').onclick=()=>{if(window.parent!==window)window.parent.postMessage('fitlab-close-sandbox',location.origin);else location.href='index.html#fitting';};document.addEventListener('visibilitychange',()=>{last=0;});window.addEventListener('pagehide',()=>cancelAnimationFrame(raf));
async function start(){try{data=(await import('./sandbox-preview-data.js')).default;selected=data.ships[0].id;$('#seek').max=data.duration;const points=data.frames.flatMap(f=>f.ships.map(s=>s.position)),xs=points.map(p=>p.x),ys=points.map(p=>p.y),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys);bounds={x:(minX+maxX)/2,y:(minY+maxY)/2,w:Math.max(10000,maxX-minX),h:Math.max(10000,maxY-minY)};for(const m of data.missiles)m.endUs=data.events.find(e=>e.kind==='MissileImpacted'&&e.entityId===m.id)?.timeUs;$('#script').textContent=data.script;for(const s of data.ships){if(!images.has(s.typeId)){const image=new Image();image.src=`https://images.evetech.net/types/${s.typeId}/icon?size=64`;images.set(s.typeId,image);}const button=document.createElement('button');button.dataset.id=s.id;const image=document.createElement('img');image.src=images.get(s.typeId).src;image.alt='';const text=document.createElement('span');text.textContent=name(s);const sub=document.createElement('small');sub.textContent=t(s.team);text.append(sub);button.append(image,text);button.onclick=()=>{selected=s.id;updateInfo();};$('#roster').append(button);}$('#loading').hidden=true;$('#play').disabled=$('#restart').disabled=false;updateInfo();setPlaying(true);raf=requestAnimationFrame(tick);}catch(e){$('#loading').textContent=t('failed');console.error(e);}

}
start();
