const words={
 'zh-CN':{title:'战斗沙盒 · 预览',intro:'脚本驱动舰队作战。完整编辑与调试功能将在后续版本开放。',back:'返回装配',replay:'引擎战斗回放',view:'重置视角',help:'拖动平移 · 滚轮缩放 · 点击舰船查看',blue:'蓝方',red:'红方',fleet:'参战舰队',scope:'固定场景演示 · 真实引擎记录。当前画面为二维投影，轨迹与特效作视觉插值，不代表完整实服战斗。',play:'播放',pause:'暂停',restart:'重播',script:'查看脚本', 'script-note':'每阵营一个策略 · 只读预览',loading:'正在读取战斗记录…',failed:'战斗记录读取失败，请刷新重试。',shield:'护盾',armor:'装甲',hull:'结构',capacitor:'电容',sample:'状态按引擎逐秒记录显示',gun:'炮击',laser:'激光',missile:'导弹',web:'电子战',rifter:'裂谷级',caracal:'狞獾级',ended:'回放结束'},
 en:{title:'Battle sandbox · Preview',intro:'Script-controlled fleets. Full editing and debugging are coming in a future version.',back:'Back to fitting',replay:'Engine battle replay',view:'Reset view',help:'Drag to pan · Scroll to zoom · Select a ship',blue:'Blue',red:'Red',fleet:'FLEET',scope:'Recorded engine demonstration. 2D projection and interpolated effects; not a complete live-game combat model.',play:'Play',pause:'Pause',restart:'Replay',script:'View script','script-note':'One policy per team · Read-only preview',loading:'Loading battle recording…',failed:'Could not load recording. Refresh to retry.',shield:'Shield',armor:'Armor',hull:'Hull',capacitor:'Capacitor',sample:'State sampled once per simulation second',gun:'Turrets',laser:'Lasers',missile:'Missiles',web:'Electronic warfare',rifter:'Rifter',caracal:'Caracal',ended:'Replay complete'},
 'zh-TW':{title:'戰鬥沙盒 · 預覽',intro:'腳本驅動艦隊作戰。完整編輯與除錯功能將在後續版本開放。',back:'返回裝配',replay:'引擎戰鬥回放',view:'重設視角',help:'拖動平移 · 滾輪縮放 · 點擊艦船查看',blue:'藍方',red:'紅方',fleet:'參戰艦隊',scope:'固定場景展示 · 真實引擎記錄。二維投影及特效插值不代表完整實服戰鬥。',play:'播放',pause:'暫停',restart:'重播',script:'查看腳本','script-note':'每陣營一個策略 · 唯讀預覽',loading:'正在讀取戰鬥記錄…',failed:'記錄讀取失敗，請重新整理。',shield:'護盾',armor:'裝甲',hull:'結構',capacitor:'電容',sample:'狀態依引擎逐秒記錄顯示',gun:'炮擊',laser:'雷射',missile:'飛彈',web:'電子戰',rifter:'裂谷級',caracal:'獰獾級',ended:'回放結束'},
 ja:{title:'戦闘サンドボックス · プレビュー',intro:'スクリプトで艦隊を操作。編集とデバッグは今後のバージョンで公開予定。',back:'装備画面へ',replay:'エンジン戦闘リプレイ',view:'視点をリセット',help:'ドラッグで移動 · ホイールで拡大 · 艦船を選択',blue:'青チーム',red:'赤チーム',fleet:'艦隊',scope:'エンジンの記録を使ったデモ。2D投影と補間演出であり、実ゲームの戦闘を完全に再現するものではありません。',play:'再生',pause:'一時停止',restart:'最初から',script:'スクリプト','script-note':'チームごとの戦略 · 読み取り専用',loading:'戦闘記録を読み込み中…',failed:'記録を読み込めません。再読み込みしてください。',shield:'シールド',armor:'アーマー',hull:'ストラクチャ',capacitor:'キャパシタ',sample:'状態はシミュレーションの1秒ごとの記録',gun:'タレット',laser:'レーザー',missile:'ミサイル',web:'電子戦',rifter:'リフター',caracal:'カラカル',ended:'再生終了'}
};
const lang=new URLSearchParams(location.search).get('lang')||'zh-CN',dict=words[lang]||words.en,t=key=>dict[key]||words.en[key]||key;
document.documentElement.lang=words[lang]?lang:'en';document.querySelectorAll('[data-text]').forEach(e=>e.textContent=t(e.dataset.text));
const $=s=>document.querySelector(s),canvas=$('#battle'),ctx=canvas.getContext('2d');
let data,time=0,playing=false,selected='blue-gun',zoom=1,pan={x:0,y:0},width=1,height=1,last=0,uiLast=-1,raf,drag=null;
const images=new Map(),color=id=>id.startsWith('blue')?'#78d2ed':'#f28e85';
const role=id=>id.endsWith('gun')?'gun':id.endsWith('laser')?'laser':id.endsWith('missile')?'missile':'web';
const name=s=>t(s.typeId===621?'caracal':'rifter')+' · '+t(role(s.id));
const scale=()=>Math.min(width/11000,height/10000)*zoom;
const project=p=>({x:width/2+p.x*scale()+pan.x,y:height/2-p.y*scale()+pan.y});
const state=()=>data.frames[Math.min(Math.floor(time),data.frames.length-1)];
function position(id){const a=state().ships.find(s=>s.id===id),b=data.frames[Math.min(Math.floor(time)+1,data.frames.length-1)].ships.find(s=>s.id===id),f=time-Math.floor(time);return project({x:a.position.x+(b.position.x-a.position.x)*f,y:a.position.y+(b.position.y-a.position.y)*f});}
function setPlaying(value){playing=value;$('#play').textContent=t(value?'pause':'play');}
function updateInfo(){
 const frame=state(),s=frame.ships.find(s=>s.id===selected),meta=data.ships.find(s=>s.id===selected);
 $('#inspect').replaceChildren();const title=document.createElement('h2');title.textContent=name(meta);$('#inspect').append(title);
 for(const layer of [...s.layers,{name:'capacitor',hitpoints:s.capacitor,capacity:s.capacitorCapacity}]){const row=document.createElement('div');row.className='meter';const label=document.createElement('label'),value=document.createElement('span');label.textContent=t(layer.name);value.textContent=Math.round(layer.hitpoints).toLocaleString(lang)+' / '+Math.round(layer.capacity).toLocaleString(lang);label.append(value);const bar=document.createElement('progress');bar.max=layer.capacity;bar.value=layer.hitpoints;row.append(label,bar);$('#inspect').append(row);}
 const note=document.createElement('small');note.className='note';note.textContent=t('sample');$('#inspect').append(note);
 $('#roster').querySelectorAll('button').forEach(e=>e.setAttribute('aria-pressed',String(e.dataset.id===selected)));
 $('#clock').textContent=`00:${time.toFixed(1).padStart(4,'0')} / 00:40`;$('#seek').value=time;
}
function stroke(a,b,c,alpha=1,lineWidth=1){ctx.globalAlpha=alpha;ctx.strokeStyle=c;ctx.lineWidth=lineWidth;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.globalAlpha=1;}
function draw(){
 ctx.clearRect(0,0,width,height);const cell=Math.max(20,1000*scale());ctx.lineWidth=1;ctx.strokeStyle='#63879a15';for(let x=(width/2+pan.x)%cell;x<width;x+=cell){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,height);ctx.stroke();}for(let y=(height/2+pan.y)%cell;y<height;y+=cell){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(width,y);ctx.stroke();}
 if(!data)return;
 for(const effect of data.effects){if(time*1e6<effect.startedAtUs||time*1e6>=Math.min(effect.expiresAtUs,effect.endedAtUs??Infinity))continue;const a=position(effect.sourceId),b=position(effect.targetId),c=effect.abilityId==='web'?'#b694ef':'#efb16c';ctx.setLineDash([4,7]);ctx.lineDashOffset=-time*20;stroke(a,b,c,.4,1.5);ctx.setLineDash([]);const f=(time*1.4)%1;ctx.strokeStyle=c;ctx.globalAlpha=(1-f)*.6;ctx.beginPath();ctx.arc(b.x,b.y,24+f*24,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1;}
 for(const e of data.events){const age=time-e.timeUs/1e6;if(age<0||age>0.6)continue;
  if(e.kind==='TurretResolved'){const a=position(e.sourceId),b=position(e.targetId),laser=role(e.sourceId)==='laser';if(laser){stroke(a,b,'#fb887f',Math.max(0,1-age/.5),3);stroke(a,b,'#ffe3ad',Math.max(0,1-age/.4),1);}else{const f=Math.min(1,age/.18),q={x:a.x+(b.x-a.x)*f,y:a.y+(b.y-a.y)*f};stroke({x:q.x-(b.x-a.x)*.07,y:q.y-(b.y-a.y)*.07},q,'#ffe3a1',1-age/.6,2);}}
  if(e.kind==='MissileImpacted'){const q=position(e.targetId);ctx.globalAlpha=1-age/.6;ctx.fillStyle='#ffd997';ctx.beginPath();ctx.arc(q.x,q.y,4+age*30,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;}
 }
 for(const m of data.missiles){const end=m.endUs??m.expiresAtUs,start=m.launchedAtUs;if(time*1e6<start||time*1e6>=end)continue;const a=project(m.launchPosition),b=position(m.targetId),f=(time*1e6-start)/(end-start),offset=(Number(m.id.split('-')[1])%5-2)*3,q={x:a.x+(b.x-a.x)*f,y:a.y+(b.y-a.y)*f+offset};stroke({x:q.x-(b.x-a.x)*.09,y:q.y-(b.y-a.y)*.09},q,'#ffc274',.7,2);ctx.fillStyle='#fff0c7';ctx.beginPath();ctx.arc(q.x,q.y,2,0,Math.PI*2);ctx.fill();}
 for(const meta of data.ships){const s=state().ships.find(s=>s.id===meta.id),q=position(meta.id),image=images.get(meta.typeId);ctx.globalAlpha=s.destroyed?.3:1;ctx.strokeStyle=color(meta.id);ctx.lineWidth=selected===meta.id?2:1;ctx.beginPath();ctx.arc(q.x,q.y,25,0,Math.PI*2);ctx.stroke();if(selected===meta.id){ctx.strokeStyle='#dcecfb35';ctx.beginPath();ctx.arc(q.x,q.y,32,0,Math.PI*2);ctx.stroke();}if(image?.complete&&image.naturalWidth)ctx.drawImage(image,q.x-20,q.y-20,40,40);else{ctx.fillStyle=color(meta.id);ctx.fillRect(q.x-8,q.y-8,16,16);}ctx.font='11px Segoe UI';ctx.textAlign='center';ctx.fillStyle=color(meta.id);ctx.fillText(name(meta),q.x,q.y+44);s.layers.forEach((l,i)=>{ctx.fillStyle='#263949';ctx.fillRect(q.x-21,q.y+28+i*3,42,2);ctx.fillStyle=['#86cfe6','#c2bba0','#b18f87'][i];ctx.fillRect(q.x-21,q.y+28+i*3,42*l.hitpoints/l.capacity,2);});ctx.globalAlpha=1;}
}
function tick(now){if(last&&playing&&!document.hidden){time=Math.min(data.duration,time+(now-last)/1000*Number($('#speed').value));if(time>=data.duration)setPlaying(false);}last=now;draw();if(data&&Math.abs(time-uiLast)>.1){updateInfo();uiLast=time;}raf=requestAnimationFrame(tick);}
new ResizeObserver(()=>{const r=canvas.getBoundingClientRect(),dpr=devicePixelRatio||1;width=r.width;height=r.height;canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);draw();}).observe(canvas);
canvas.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.4,Math.min(4,zoom*Math.exp(-e.deltaY*.001)));},{passive:false});
canvas.onpointerdown=e=>{drag={x:e.clientX,y:e.clientY,px:pan.x,py:pan.y};canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(drag)pan={x:drag.px+e.clientX-drag.x,y:drag.py+e.clientY-drag.y};};canvas.onpointerup=e=>{if(drag&&Math.hypot(e.clientX-drag.x,e.clientY-drag.y)<5&&data){const r=canvas.getBoundingClientRect(),hit=data.ships.find(s=>{const q=position(s.id);return Math.hypot(q.x-(e.clientX-r.left),q.y-(e.clientY-r.top))<28;});if(hit){selected=hit.id;updateInfo();}}drag=null;};canvas.onpointercancel=()=>drag=null;
$('#reset-view').onclick=()=>{zoom=1;pan={x:0,y:0};};$('#play').onclick=()=>{if(time>=data.duration)time=0;setPlaying(!playing);};$('#restart').onclick=()=>{time=0;uiLast=-1;setPlaying(true);};$('#seek').oninput=e=>{time=Number(e.target.value);uiLast=-1;updateInfo();};$('#script-toggle').onclick=()=>{$('#script-panel').hidden=!$('#script-panel').hidden;$('#script-toggle').setAttribute('aria-expanded',String(!$('#script-panel').hidden));};$('#close').onclick=()=>{if(window.parent!==window)window.parent.postMessage('fitlab-close-sandbox',location.origin);else location.href='index.html#fitting';};document.addEventListener('visibilitychange',()=>{last=0;});window.addEventListener('pagehide',()=>cancelAnimationFrame(raf));
async function start(){try{data=(await import('./sandbox-preview-data.js')).default;for(const m of data.missiles)m.endUs=data.events.find(e=>e.kind==='MissileImpacted'&&e.entityId===m.id)?.timeUs;$('#script').textContent=data.script;for(const s of data.ships){if(!images.has(s.typeId)){const image=new Image();image.src=`https://images.evetech.net/types/${s.typeId}/icon?size=64`;images.set(s.typeId,image);}const button=document.createElement('button');button.dataset.id=s.id;const image=document.createElement('img');image.src=images.get(s.typeId).src;image.alt='';const text=document.createElement('span');text.textContent=name(s);const sub=document.createElement('small');sub.textContent=t(s.team);text.append(sub);button.append(image,text);button.onclick=()=>{selected=s.id;updateInfo();};$('#roster').append(button);}$('#loading').hidden=true;$('#play').disabled=$('#restart').disabled=false;updateInfo();setPlaying(true);raf=requestAnimationFrame(tick);}catch(e){$('#loading').textContent=t('failed');console.error(e);}

}
start();
