import {calculateBaseStats,damageNames} from './stats.js';
const escape=t=>String(t).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function mountStats(root,ship,slots,catalog,ehp,onToggle){
 const s=calculateBaseStats(ship,slots,catalog),a=ship.attrs,unit=ehp?'EHP/s':'HP/s';
 const lookup=id=>catalog.find(t=>t.id===id),active=slots.filter(x=>x.online&&x.item).map(x=>({t:lookup(x.item),ammo:lookup(x.ammo)}));
 const scope=[['数据范围','基础属性'],['技能 / 装备加成','未接入']];
 const tip=(title,result,terms,conditions=scope)=>`tabindex="0" data-explain="${escape(JSON.stringify({title,result,terms,conditions}))}"`;
 const row=(label,value,terms,conditions=scope)=>`<div class="stat-row" ${tip(label,value,terms,conditions)}><span>${label}</span><b>${value}</b></div>`;
 const heading=(title,note)=>`<div class="panel-title">${title}<small>${note}</small></div>`;
 const bars=(values,termFactory)=>`<div class="damage-bars">${values.map((v,i)=>`<div class="damage-cell" ${tip(damageNames[i],v.toFixed(1)+'%',termFactory(v,i))}><span class="damage-label">${damageNames[i]}</span><div class="mini-bar damage-${i}" role="progressbar" aria-label="${damageNames[i]}" aria-valuenow="${v.toFixed(1)}" aria-valuemin="0" aria-valuemax="100"><i style="width:${Math.min(100,Math.max(0,v))}%"></i><b>${v.toFixed(0)}%</b></div></div>`).join('')}</div>`;
 const weapons=active.filter(x=>x.t.effects.includes(42)&&x.ammo&&x.t.attrs[51]>0);
 const weaponTerms=mode=>weapons.flatMap(({t,ammo})=>{const hit=[114,118,117,116].reduce((n,id)=>n+(ammo.attrs[id]||0),0),alpha=hit*(t.attrs[64]||1);return [[t.name,mode==='dps'?`+ ${(alpha/(t.attrs[51]/1000)).toFixed(2)} HP/s`:`+ ${alpha.toFixed(2)} HP`,'source'],['弹药伤害',`${hit} HP`],['伤害倍率',`× ${t.attrs[64]||1}`],...(mode==='dps'?[['周期',`÷ ${t.attrs[51]/1000} s`]]:[])]});
 const repairTerms=(attr,factor)=>{const terms=active.filter(x=>x.t.attrs[attr]&&x.t.attrs[73]).flatMap(({t})=>[[t.name,`+ ${(t.attrs[attr]/(t.attrs[73]/1000)).toFixed(2)} HP/s`,'source'],['单周期修量',`${t.attrs[attr]} HP`],['周期',`÷ ${t.attrs[73]/1000} s`]]);if(!terms.length)terms.push(['在线维修模块','0']);if(ehp)terms.push(['抗性折算',`× ${factor.toFixed(4)}`]);return terms};
 const shieldFactor=ehp?1/s.layers[0].mean:1,armorFactor=ehp?1/s.layers[1].mean:1;
 const peakTerms=(capacity,seconds,factor=1)=>[['容量',capacity],['回充时间',`÷ ${seconds} s`],['峰值系数','× 2.5'],...(ehp&&factor!==1?[['抗性折算',`× ${factor.toFixed(4)}`]]:[])];
 const uniform=[['来伤分布','电 / 热 / 动 / 爆：各 25%'],...scope];
 root.innerHTML=heading('攻击','基础 · 不含换弹')+`<div class="stat-block">${row('DPS',s.dps.toFixed(1),weaponTerms('dps').length?weaponTerms('dps'):[['在线已装填炮塔','0']], [['命中 / 换弹','未计入'],...scope])}${row('齐射伤害 · DPH',s.alpha.toFixed(1)+' HP',weaponTerms('alpha').length?weaponTerms('alpha'):[['在线已装填炮塔','0']])}${bars(s.damage.map(v=>s.dps?v/s.dps*100:0),(v,i)=>[[damageNames[i]+' DPS',s.damage[i].toFixed(2)],['总 DPS',s.dps?`÷ ${s.dps.toFixed(2)}`:'0 · 无输出'],['百分比','× 100%']])}</div>`+
 heading('防御',`<button id="defense-mode" aria-label="切换 HP 与 EHP">${ehp?'EHP':'HP'} ⇄</button>`)+`<div class="stat-block"><div class="profile-note">${ehp?'均匀来伤 · 电热动爆各 25%':'裸船基础抗性与血量'}</div>${s.layers.map(l=>`<div class="defense-layer">${row(l.name,`${(ehp?l.ehp:l.hp).toFixed(0)} ${ehp?'EHP':'HP'}`,[['基础血量',`${l.hp} HP`],...(ehp?[['加权伤害共振',`÷ ${l.mean.toFixed(4)}`]]:[])],ehp?uniform:scope)}${bars(l.resonance.map(r=>(1-r)*100),(v,i)=>[['基准','100%'],['伤害共振',`− ${(l.resonance[i]*100).toFixed(1)}%`]])}</div>`).join('')}${row('总'+(ehp?' EHP':' HP'),s.layers.reduce((n,l)=>n+(ehp?l.ehp:l.hp),0).toFixed(0),s.layers.map(l=>[l.name,`+ ${(ehp?l.ehp:l.hp).toFixed(2)} ${ehp?'EHP':'HP'}`]),ehp?uniform:scope)}${row('主动回盾',(s.shieldRepair*shieldFactor).toFixed(2)+' '+unit,repairTerms(68,shieldFactor),[['运行方式','连续启动'],['电容限制','未计入'],...(ehp?uniform:scope)])}${row('装甲维修',(s.armorRepair*armorFactor).toFixed(2)+' '+unit,repairTerms(84,armorFactor),[['运行方式','连续启动'],['电容限制','未计入'],...(ehp?uniform:scope)])}${row('被动回盾 · 峰值',(s.shieldPeak*shieldFactor).toFixed(2)+' '+unit,peakTerms(a[263]+' HP',a[479]/1000,shieldFactor),[['峰值位置','25% 护盾'],['满盾回充','0 HP/s'],...(ehp?uniform:scope)])}</div>`+
 heading('电容','裸船 · 连续启动估算')+`<div class="stat-block">${row('容量',a[482]+' GJ',[['舰船基础',a[482]+' GJ']])}${row('回充时间',a[55]/1000+' s',[['基础时间',a[55]+' ms'],['单位换算','÷ 1000']])}${row('峰值回充',s.capPeak.toFixed(2)+' GJ/s',peakTerms(a[482]+' GJ',a[55]/1000),[['峰值位置','25% 电量'],...scope])}${row('模块耗电',s.capUse.toFixed(2)+' GJ/s',active.filter(({t,ammo})=>t.attrs[6]&&(t.attrs[73]||t.attrs[51])&&(!t.effects.includes(42)||ammo)).flatMap(({t})=>[[t.name,`+ ${(t.attrs[6]/((t.attrs[73]||t.attrs[51])/1000)).toFixed(2)} GJ/s`,'source'],['启动耗电',`${t.attrs[6]} GJ`],['周期',`÷ ${(t.attrs[73]||t.attrs[51])/1000} s`]]),[['运行方式','连续启动'],['稳定性','未模拟'],...scope])}</div>`+
 heading('机动','裸船基础值')+`<div class="stat-block">${row('最大速度',a[37]+' m/s',[['舰船基础',a[37]+' m/s']])}${row('信号半径',a[552]+' m',[['舰船基础',a[552]+' m']])}</div>`+
 heading('锁定','裸船基础值')+`<div class="stat-block">${row('锁定距离',(a[76]/1000).toFixed(1)+' km',[['舰船基础',a[76]+' m'],['单位换算','÷ 1000']])}${row('锁定目标数',a[192],[['舰船基础',a[192]]])}${row('扫描分辨率',a[564]+' mm',[['舰船基础',a[564]+' mm']])}</div>`;
 root.querySelector('#defense-mode').onclick=onToggle;
}
