from pathlib import Path
p=Path('engine-view.js');s=p.read_text(encoding='utf-8');s=s.replace('const row=(name,value,terms)=>`<div class="stat-row" ${tip(name,value,terms)}>', 'const row=(name,value,terms)=>`<div class="stat-row" ${name===\'锁定目标数\'&&Number(value)===raw[192]?\'\':tip(name,value,terms)}>')
s=s.replace('const bars=(values,title)=>', 'const bars=(values,title,baselines=null)=>')
s=s.replace('${tip(names[i]+\' · \'+title,(v*100).toFixed(1)+\'%\',[[\'比例\',(v*100).toFixed(2)+\'%\']])}', '${baselines&&Math.abs(v-baselines[i])<0.00001?\'\':tip(names[i]+\' · \'+title,(v*100).toFixed(1)+\'%\',[[\'比例\',(v*100).toFixed(2)+\'%\']])}')
s=s.replace('return {name,hp,resist,mean,ehp:hp/mean}', "return {name,hp,resist,mean,ehp:hp/mean,baseResist:({shield:[271,274,273,272],armor:[267,270,269,268],structure:[113,110,109,111]})[k].map(id=>1-raw[id])}")
s=s.replace("${bars(l.resist,'抗性')}", "${bars(l.resist,'抗性',l.baseResist)}")
p.write_text(s,encoding='utf-8')
p=Path('app.js');s=p.read_text(encoding='utf-8');s=s.replace("const capacity=attributeDetail(name+' · 上限',max,unit,attr,a,catalog,fitRecord.characterName);", "const capacity=attributeDetail(name+' · 上限',max,unit,attr,a,catalog,fitRecord.characterName),capacityChanged=Math.abs(max-(ship.attrs[attr==='cpuOutput'?48:11]||0))>0.001;")
s=s.replace("null,usage],['上限',`${max} ${unit}`,null,capacity]", "null,value?usage:null],['上限',`${max} ${unit}`,null,capacityChanged?capacity:null]")
s=s.replace('tabindex="0" data-explain="${esc(JSON.stringify(detail))}"><label>${name}', '${value||capacityChanged?`tabindex="0" data-explain="${esc(JSON.stringify(detail))}"`:\'\'}><label>${name}')
p.write_text(s,encoding='utf-8')
