import {getLocale} from './i18n.js';
export const velocityArrowLength=(speed,maxSpeed)=>maxSpeed>0?120*Math.max(0,Math.min(1,speed/maxSpeed)):0;
export const velocityFromArrowLength=(length,maxSpeed)=>maxSpeed>0?maxSpeed*Math.max(0,Math.min(1,length/120)):0;
export function formatTargetDistance(m){return m<1000?m.toLocaleString(getLocale(),{maximumFractionDigits:2})+' m':(m/1000).toLocaleString(getLocale(),{maximumFractionDigits:2})+' km'}
export function rotationPeriod(angular){if(angular<=0)return '角速度为 0，不发生绕转';const seconds=2*Math.PI/angular,unit=seconds<60?'秒':seconds<3600?'分钟':'小时',value=seconds/(seconds<60?1:seconds<3600?60:3600);return '约 '+value.toLocaleString(getLocale(),{maximumFractionDigits:2})+' '+unit+'转一圈（按当前角速度）'}
export function geometryValues(g){const distance=Math.hypot(g.x,g.y),speed=Math.hypot(g.vx,g.vy);return {distance,speed,angular:distance>0?Math.abs(g.x*g.vy-g.y*g.vx)/(distance*distance):0}}
export function mountTargetPlane(root,initial){
 const d=Math.max(0,initial.distance??10000),speed=initial.speed??200,tangent=Math.min(speed,(initial.angular??.01)*d);
 let g=initial.geometry?{...initial.geometry}:{x:d,y:0,vx:Math.sqrt(Math.max(0,speed*speed-tangent*tangent)),vy:tangent};
 if(!Object.values(g).every(Number.isFinite))g={x:10000,y:0,vx:0,vy:200};
 const range=500000;let drag=null;let zoom=1,viewX=0,viewY=0,panStart=null;let maxSpeed=null,speedStatus='选择目标装配后设置速度';let direction={x:1,y:0};
 root.innerHTML='<div class="target-plane-help">滚轮缩放 · 左键拖动空白平移 · 拖动敌舰及速度箭头</div><svg class="target-plane" viewBox="0 0 600 340" aria-label="靶标位置与相对速度设置"><defs><pattern id="target-grid" width="30" height="30" patternUnits="userSpaceOnUse"><path d="M30 0H0V30" fill="none" stroke="currentColor" stroke-opacity=".12"/></pattern><marker id="target-arrow" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0 0L6 3L0 6" fill="none" stroke="currentColor"/></marker></defs><rect width="600" height="340" fill="url(#target-grid)"/><path d="M300 0V340M0 170H600" class="target-axis"/><circle cx="300" cy="170" r="85" class="target-ring"/><circle cx="300" cy="170" r="170" class="target-ring"/><line class="target-separation"/><text class="target-distance-label" text-anchor="middle"/><line class="target-vector" marker-end="url(#target-arrow)"/><g class="own-entity"><path d="M300 158L290 180L300 176L310 180Z"/><text x="300" y="200" text-anchor="middle">本舰</text></g><g class="enemy-entity" data-handle="position" tabindex="0" role="button" aria-label="拖动敌舰位置，方向键微调"><circle r="18" class="target-hit"/><path d="M0 -11L10 0L0 11L-10 0Z"/><text y="-22" text-anchor="middle">敌舰</text></g><g class="velocity-handle" data-handle="velocity" tabindex="0" role="button" aria-label="拖动速度矢量，方向键微调"><circle r="18" class="target-hit"/><circle r="5"/></g></svg><div class="target-plane-readouts"></div><div class="target-speed-limit" role="status"></div><div class="target-plane-scales"><span class="target-fixed-range">范围 0–500 km</span><span class="target-view-scale"></span><button type="button" data-reset-view>重置视角</button><span title="从舰船图标外沿起计，120 像素对应双方最大相对速度；图标内不计速度">速度箭头 · 自适应上限</span><button type="button" data-stop>停止</button><button type="button" data-tangent>横向飞行</button></div>';
 const svg=root.querySelector('svg'),pos=root.querySelector('.enemy-entity'),vel=root.querySelector('.velocity-handle');
 const fmt=(v,n=2)=>v.toLocaleString(getLocale(),{maximumFractionDigits:n});
 const screenScale=()=>{const m=svg.getScreenCTM();return Math.hypot(m.a,m.b)};
 const iconClearance=dir=>16*screenScale()/zoom/Math.max(Math.abs(dir.x),Math.abs(dir.y))+8;
 function coordinates(){const k=170/range,p={x:300+g.x*k,y:170-g.y*k},speed=Math.hypot(g.vx,g.vy);if(speed>0)direction={x:g.vx/speed,y:g.vy/speed};const length=(iconClearance(direction)+velocityArrowLength(speed,maxSpeed))/screenScale();return {p,end:{x:p.x+direction.x*length,y:p.y-direction.y*length}}}

 function paint(){svg.setAttribute('viewBox',viewX+' '+viewY+' '+600/zoom+' '+340/zoom);root.querySelector('.own-entity').setAttribute('transform','translate(300 170) scale('+1/zoom+') translate(-300 -170)');root.querySelector('.target-view-scale').textContent='视角 ×'+fmt(zoom,1);const {p,end}=coordinates();pos.setAttribute('transform','translate('+p.x+' '+p.y+') scale('+1/zoom+')');vel.setAttribute('transform','translate('+end.x+' '+end.y+') scale('+1/zoom+')');for(const [selector,a,b] of [['.target-separation',{x:300,y:170},p],['.target-vector',p,end]]){const l=root.querySelector(selector);l.setAttribute('x1',a.x);l.setAttribute('y1',a.y);l.setAttribute('x2',b.x);l.setAttribute('y2',b.y)}const v=geometryValues(g),distanceLabel=root.querySelector('.target-distance-label');distanceLabel.textContent=formatTargetDistance(v.distance);distanceLabel.setAttribute('transform','translate('+((300+p.x)/2)+' '+((170+p.y)/2-9/zoom)+') scale('+1/zoom+')');root.querySelector('.target-speed-limit').textContent=speedStatus;root.querySelectorAll('[data-tangent],[data-scale=velocity]').forEach(e=>e.disabled=maxSpeed===null);vel.setAttribute('aria-disabled',String(maxSpeed===null));root.querySelector('.target-plane-readouts').innerHTML='<span>距离 <b>'+formatTargetDistance(v.distance)+'</b></span><span>相对速度 <b>'+fmt(v.speed)+' m/s</b></span><span class="target-angular-info" tabindex="0">角速度 <b>'+fmt(v.angular,5)+' rad/s</b><span class="target-period-tooltip" role="tooltip">'+rotationPeriod(v.angular)+'</span></span>'}
 function bound(){let d=Math.hypot(g.x,g.y);if(d<1e-6){g.x=0;g.y=0}else if(d>range){g.x*=range/d;g.y*=range/d}const v=Math.hypot(g.vx,g.vy);if(maxSpeed!==null&&v>maxSpeed){g.vx*=maxSpeed/v;g.vy*=maxSpeed/v}}
 const point=e=>new DOMPoint(e.clientX,e.clientY).matrixTransform(svg.getScreenCTM().inverse());
 svg.addEventListener('wheel',e=>{e.preventDefault();e.stopPropagation();if(drag)return;const pt=point(e),next=Math.max(1,Math.min(1000,zoom*Math.exp(-Math.max(-120,Math.min(120,e.deltaY*(e.deltaMode===1?16:e.deltaMode===2?340:1)))*.003)));viewX=pt.x-(pt.x-viewX)*zoom/next;viewY=pt.y-(pt.y-viewY)*zoom/next;zoom=next;if(zoom===1){viewX=0;viewY=0}paint()},{passive:false});
 svg.onpointerdown=e=>{if(e.button!==0)return;if(e.target.closest('[data-health]'))return;const h=e.target.closest('[data-handle]');e.preventDefault();if(h?.dataset.handle==='velocity'&&maxSpeed===null)return;drag=h?.dataset.handle||'pan';const pt=point(e),p=coordinates().p;panStart={clientX:e.clientX,clientY:e.clientY,viewX,viewY,offsetX:pt.x-p.x,offsetY:pt.y-p.y};svg.setPointerCapture(e.pointerId)};
 svg.onpointermove=e=>{if(!drag)return;if(drag==='pan'){const r=svg.getBoundingClientRect();viewX=panStart.viewX-(e.clientX-panStart.clientX)*600/zoom/r.width;viewY=panStart.viewY-(e.clientY-panStart.clientY)*340/zoom/r.height;paint();return}const pt=point(e),x=pt.x,y=pt.y;if(drag==='position'){g.x=(x-panStart.offsetX-300)*range/170;g.y=(170-y+panStart.offsetY)*range/170}else{const {p}=coordinates();const dx=x-p.x,dy=p.y-y,len=Math.hypot(dx,dy),nextDirection=len?{x:dx/len,y:dy/len}:direction,speed=velocityFromArrowLength(len*screenScale()-iconClearance(nextDirection),maxSpeed);direction=nextDirection;g.vx=direction.x*speed;g.vy=direction.y*speed}bound();paint()};
 svg.onpointerup=svg.onpointercancel=svg.onlostpointercapture=()=>{drag=null;panStart=null;paint()};
 root.querySelector('[data-reset-view]').onclick=()=>{zoom=1;viewX=viewY=0;paint()};
 root.querySelectorAll('[data-handle]').forEach(h=>h.onkeydown=e=>{if(!['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();if(h.dataset.handle==='velocity'&&maxSpeed===null)return;const axis=e.key==='ArrowLeft'||e.key==='ArrowRight'?'x':'y',sign=e.key==='ArrowLeft'||e.key==='ArrowDown'?-1:1;g[(h.dataset.handle==='velocity'?'v':'')+axis]+=sign*(h.dataset.handle==='velocity'?(maxSpeed||0)/100:range/50/zoom)*(e.shiftKey?.1:1);bound();paint()});
 root.querySelector('[data-stop]').onclick=()=>{g.vx=g.vy=0;paint()};root.querySelector('[data-tangent]').onclick=()=>{const v=Math.hypot(g.vx,g.vy)||Math.min(200,maxSpeed??0),r=Math.hypot(g.x,g.y);g.vx=r?-g.y/r*v:0;g.vy=r?g.x/r*v:v;bound();paint()};bound();paint();
 const observer=new ResizeObserver(()=>{if(root.isConnected)paint();else observer.disconnect()});observer.observe(svg);
 return {setSpeedLimit(limit,message){maxSpeed=Number.isFinite(limit)?Math.max(0,limit):null;speedStatus=message;if(maxSpeed!==null){bound()}paint()},value:()=>({...geometryValues(g),geometry:{...g}})};
}
