import {getLocale} from './i18n.js';
export const velocityArrowLength=(speed,scaleSpeed)=>scaleSpeed>0?120*Math.max(0,speed/scaleSpeed):0;
export const velocityFromArrowLength=(length,scaleSpeed)=>scaleSpeed>0?scaleSpeed*Math.max(0,length/120):0;
export function formatTargetDistance(m){return m<1000?m.toLocaleString(getLocale(),{maximumFractionDigits:2})+' m':(m/1000).toLocaleString(getLocale(),{maximumFractionDigits:2})+' km'}
export function rotationPeriod(angular){if(angular<=0)return '角速度为 0，不发生绕转';const seconds=2*Math.PI/angular,unit=seconds<60?'秒':seconds<3600?'分钟':'小时',value=seconds/(seconds<60?1:seconds<3600?60:3600);return '约 '+value.toLocaleString(getLocale(),{maximumFractionDigits:2})+' '+unit+'转一圈（按当前角速度）'}
export function geometryValues(g){const distance=Math.hypot(g.x,g.y),speed=Math.hypot(g.vx,g.vy),rx=g.vx-(g.ownVx??0),ry=g.vy-(g.ownVy??0);return {distance,speed,angular:distance>0?Math.abs(g.x*ry-g.y*rx)/(distance*distance):0}}
export function mountTargetPlane(root,initial){
 const d=Math.max(0,initial.distance??10000),speed=initial.speed??200,tangent=Math.min(speed,(initial.angular??.01)*d);
 let g=initial.geometry?{...initial.geometry}:{x:d,y:0,vx:Math.sqrt(Math.max(0,speed*speed-tangent*tangent)),vy:tangent};
 if(!Object.values(g).every(Number.isFinite))g={x:10000,y:0,vx:0,vy:200};
 g.ownVx??=0;g.ownVy??=0;
 const sources={support:{...(initial.supportGeometry||{x:0,y:initial.supportDistance??10000}),visible:false},hostile:{...(initial.hostileGeometry||{x:0,y:-(initial.hostileDistance??10000)}),visible:false}};
 const range=500000;let drag=null;let zoom=5,viewX=240,viewY=136,panStart=null;let velocityScale=Number.isFinite(initial.velocityScale)&&initial.velocityScale>0?Math.max(.000001,Math.min(1e9,initial.velocityScale)):null;let ownMaxSpeed=null;let maxSpeed=null,speedStatus='选择目标装配后设置速度';let direction={x:1,y:0};
 root.innerHTML='<svg class="target-plane" viewBox="0 0 600 340" aria-label="情景位置与双方绝对速度设置"><defs><pattern id="target-grid" width="30" height="30" patternUnits="userSpaceOnUse"><path d="M30 0H0V30" fill="none" stroke="currentColor" stroke-opacity=".12" stroke-width=".15"/></pattern><marker id="target-arrow" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0 0L6 3L0 6" fill="none" stroke="currentColor"/></marker></defs><rect width="600" height="340" fill="url(#target-grid)"/><path d="M300 0V340M0 170H600" class="target-axis"/><circle cx="300" cy="170" r="85" class="target-ring"/><circle cx="300" cy="170" r="170" class="target-ring"/><line class="target-separation"/><text class="target-distance-label" text-anchor="middle"/><line class="target-vector" marker-end="url(#target-arrow)"/><g class="own-entity"><path d="M300 158L290 180L300 176L310 180Z"/><text x="300" y="200" text-anchor="middle">本舰</text></g><g class="enemy-entity" data-handle="position" tabindex="0" role="button" aria-label="拖动敌舰位置，方向键微调"><circle r="18" class="target-hit"/><path d="M0 -11L10 0L0 11L-10 0Z"/><text y="-22" text-anchor="middle">敌舰</text></g><g class="velocity-handle" data-handle="velocity" tabindex="0" role="button" aria-label="拖动目标绝对速度矢量，方向键微调"><circle r="18" class="target-hit"/><circle r="5"/></g><text class="canvas-speed-label" text-anchor="middle"></text><text class="canvas-angular-label" text-anchor="middle"></text></svg><div class="canvas-hint">右键放置舰船</div><div class="canvas-scale"><i></i><span></span></div><div class="canvas-tools"><span class="canvas-speed-warning" hidden title="速度条件未就绪">!</span><button type="button" data-reset-view aria-label="复位视角" title="复位视角">⌖</button><details class="canvas-help"><summary aria-label="操作与计算说明" title="操作与计算说明">?</summary><div><b>操作</b><p>右键放置或编辑舰船。拖动舰船调整距离，拖动两艘船各自的箭头调整绝对速度。导弹使用目标绝对速度，炮台角速度由双方速度差计算。滚轮缩放，拖空地平移。拖住速度箭头时滚轮改为调整速度比例尺：向下滚动，箭头长度不变、速度减小。</p><b>计算条件</b><p>静态估算，供装配参考。当前传电与毁电来源假设持续运转，未联算来源缺电停机。</p><p>仅本地保存，不随图片分享。</p></div></details></div>';
 const svg=root.querySelector('svg'),pos=root.querySelector('.enemy-entity'),vel=root.querySelector('.velocity-handle');
 const ownVel=vel.cloneNode(true);ownVel.classList.add('own-velocity-handle');ownVel.dataset.handle='ownVelocity';ownVel.setAttribute('aria-label','拖动本舰绝对速度矢量，方向键微调');svg.append(ownVel);
 const ownVector=root.querySelector('.target-vector').cloneNode(true);ownVector.classList.add('own-velocity-vector');ownVector.style.stroke='var(--accent)';ownVector.style.color='var(--accent)';ownVector.style.pointerEvents='none';svg.append(ownVector);
 ownVel.style.fill='var(--accent)';
 const ownLabel=root.querySelector('.canvas-speed-label').cloneNode(true);ownLabel.classList.add('own-speed-label');ownLabel.style.fill='var(--accent)';svg.append(ownLabel);
 const isVelocity=()=>drag==='velocity'||drag==='ownVelocity';
 const dragLimit=()=>drag==='ownVelocity'?ownMaxSpeed:maxSpeed;
 const velocityKeys=()=>drag==='ownVelocity'?['ownVx','ownVy']:['vx','vy'];
 for(const key of ['support','hostile']){const group=document.createElementNS('http://www.w3.org/2000/svg','g');group.setAttribute('class','scenario-source '+key);group.dataset.handle=key;group.setAttribute('tabindex','0');group.setAttribute('role','button');group.setAttribute('aria-label',key==='support'?'传电来源，拖动或方向键调整位置':'毁电来源，拖动或方向键调整位置');svg.append(group);}
 const paintSources=()=>{for(const [key,source] of Object.entries(sources)){const node=root.querySelector('.scenario-source.'+key);node.style.display=source.visible?'':'none';node.setAttribute('transform','translate('+(300+source.x*170/range)+' '+(170-source.y*170/range)+') scale('+1/zoom+')');const label=node.querySelector('[data-distance]');if(label)label.textContent=formatTargetDistance(Math.hypot(source.x,source.y));}root.dispatchEvent(new CustomEvent('scenario-geometry'));};
 const fmt=(v,n=2)=>v.toLocaleString(getLocale(),{maximumFractionDigits:n});
 const screenScale=()=>{const m=svg.getScreenCTM();return Math.hypot(m.a,m.b)};
 const iconClearance=dir=>16*screenScale()/zoom/Math.max(Math.abs(dir.x),Math.abs(dir.y))+8;
 function coordinates(own=false){const k=170/range,p=own?{x:300,y:170}:{x:300+g.x*k,y:170-g.y*k},vx=own?g.ownVx:g.vx,vy=own?g.ownVy:g.vy,speed=Math.hypot(vx,vy);if(speed>0)direction={x:vx/speed,y:vy/speed};else direction=own?{x:-1,y:0}:{x:1,y:0};const length=(iconClearance(direction)+velocityArrowLength(speed,velocityScale))/screenScale();return {p,end:{x:p.x+direction.x*length,y:p.y-direction.y*length}}}

 function paint(){paintSources();svg.setAttribute('viewBox',viewX+' '+viewY+' '+600/zoom+' '+340/zoom);root.querySelector('.own-entity').setAttribute('transform','translate(300 170) scale('+1/zoom+') translate(-300 -170)');const scaleMeters=80/screenScale()*range/170;const scale=root.querySelector('.canvas-scale');scale.classList.toggle('velocity-scale',isVelocity());scale.title=isVelocity()?'速度比例尺 · 滚轮调整':'距离比例尺';scale.querySelector('span').textContent=isVelocity()?fmt(velocityFromArrowLength(80,velocityScale))+' m/s':formatTargetDistance(scaleMeters);const {p,end}=coordinates();pos.setAttribute('transform','translate('+p.x+' '+p.y+') scale('+1/zoom+')');vel.setAttribute('transform','translate('+end.x+' '+end.y+') scale('+1/zoom+')');for(const [selector,a,b] of [['.target-separation',{x:300,y:170},p],['.target-vector',p,end]]){const l=root.querySelector(selector);l.setAttribute('x1',a.x);l.setAttribute('y1',a.y);l.setAttribute('x2',b.x);l.setAttribute('y2',b.y)}const v=geometryValues(g),distanceLabel=root.querySelector('.target-distance-label');distanceLabel.textContent=formatTargetDistance(v.distance);distanceLabel.setAttribute('transform','translate('+((300+p.x)/2)+' '+(Math.hypot(p.x-300,p.y-170)*screenScale()<150?Math.min(170,p.y)-46/zoom:(170+p.y)/2-12/zoom)+') scale('+1/zoom+')');const speedLabel=root.querySelector('.canvas-speed-label'),angularLabel=root.querySelector('.canvas-angular-label');
 speedLabel.textContent='目标 '+fmt(v.speed)+' m/s';speedLabel.setAttribute('transform','translate('+end.x+' '+(end.y-14/zoom)+') scale('+1/zoom+')');
 angularLabel.textContent='ω '+fmt(v.angular,5)+' rad/s';angularLabel.setAttribute('transform','translate('+p.x+' '+(p.y+61/zoom)+') scale('+1/zoom+')');
 angularLabel.setAttribute('aria-label','角速度 '+fmt(v.angular,5)+' rad/s');
 const own=coordinates(true);ownVel.setAttribute('transform','translate('+own.end.x+' '+own.end.y+') scale('+1/zoom+')');
 for(const [key,value] of Object.entries({x1:own.p.x,y1:own.p.y,x2:own.end.x,y2:own.end.y}))ownVector.setAttribute(key,value);
 ownLabel.textContent='本舰 '+fmt(Math.hypot(g.ownVx,g.ownVy))+' m/s';ownLabel.setAttribute('transform','translate('+own.end.x+' '+(own.end.y-14/zoom)+') scale('+1/zoom+')');
 ownVel.setAttribute('aria-disabled',String(ownMaxSpeed===null));
 vel.setAttribute('aria-disabled',String(maxSpeed===null));
 const warning=root.querySelector('.canvas-speed-warning');warning.hidden=maxSpeed!==null||pos.style.display==='none';warning.title=speedStatus;
 }

 function bound(){let d=Math.hypot(g.x,g.y);if(d<1e-6){g.x=0;g.y=0}else if(d>range){g.x*=range/d;g.y*=range/d}for(const [x,y,limit] of [['vx','vy',maxSpeed],['ownVx','ownVy',ownMaxSpeed]]){const v=Math.hypot(g[x],g[y]);if(limit!==null&&v>limit){g[x]*=limit/v;g[y]*=limit/v}}}
 const point=e=>new DOMPoint(e.clientX,e.clientY).matrixTransform(svg.getScreenCTM().inverse());
 svg.addEventListener('wheel',e=>{e.preventDefault();e.stopPropagation();const delta=Math.max(-120,Math.min(120,e.deltaY*(e.deltaMode===1?16:e.deltaMode===2?340:1)));
 if(isVelocity()){
  const limit=dragLimit(),[vx,vy]=velocityKeys();if(!(velocityScale>0)||!(limit>0)||delta===0)return;
  const speed=Math.hypot(g[vx],g[vy]);
  let nextScale=Math.max(.000001,Math.min(1e9,velocityScale*Math.exp(-delta*.003)));
  // Saturate speed and scale together: the arrow must not jump at the ship's limit.
  if(speed>0)nextScale=Math.min(nextScale,velocityScale*limit/speed);
  const ratio=nextScale/velocityScale;if(Math.abs(ratio-1)<1e-12)return;
  g[vx]*=ratio;g[vy]*=ratio;velocityScale=nextScale;paint();changed();return;
 }
 if(drag)return;const pt=point(e),next=Math.max(1,Math.min(1000,zoom*Math.exp(-delta*.003)));viewX=pt.x-(pt.x-viewX)*zoom/next;viewY=pt.y-(pt.y-viewY)*zoom/next;zoom=next;if(zoom===1){viewX=0;viewY=0}paint()},{passive:false});
 svg.onpointerdown=e=>{if(e.button!==0)return;if(e.target.closest('[data-health]'))return;const h=e.target.closest('[data-handle]');e.preventDefault();h?.focus({preventScroll:true});if(h?.dataset.handle==='velocity'&&maxSpeed===null||h?.dataset.handle==='ownVelocity'&&ownMaxSpeed===null)return;drag=h?.dataset.handle||'pan';const pt=point(e),p=sources[drag]?{x:300+sources[drag].x*170/range,y:170-sources[drag].y*170/range}:coordinates(drag==='ownVelocity').p;panStart={clientX:e.clientX,clientY:e.clientY,viewX,viewY,offsetX:pt.x-p.x,offsetY:pt.y-p.y};svg.setPointerCapture(e.pointerId);paint()};
 svg.onpointermove=e=>{if(!drag)return;if(drag==='pan'){const r=svg.getBoundingClientRect();viewX=panStart.viewX-(e.clientX-panStart.clientX)*600/zoom/r.width;viewY=panStart.viewY-(e.clientY-panStart.clientY)*340/zoom/r.height;paint();return}const pt=point(e),x=pt.x,y=pt.y;if(sources[drag]){const source=sources[drag];source.x=(x-panStart.offsetX-300)*range/170;source.y=(170-y+panStart.offsetY)*range/170;const d=Math.hypot(source.x,source.y);if(d>range){source.x*=range/d;source.y*=range/d}paint();changed();return}else if(drag==='position'){g.x=(x-panStart.offsetX-300)*range/170;g.y=(170-y+panStart.offsetY)*range/170}else{const {p}=coordinates(drag==='ownVelocity');const dx=x-p.x,dy=p.y-y,len=Math.hypot(dx,dy),nextDirection=len?{x:dx/len,y:dy/len}:direction,speed=velocityFromArrowLength(len*screenScale()-iconClearance(nextDirection),velocityScale);direction=nextDirection;const [vx,vy]=velocityKeys();g[vx]=direction.x*speed;g[vy]=direction.y*speed}bound();paint();changed()};
 svg.onpointerup=svg.onpointercancel=svg.onlostpointercapture=()=>{drag=null;panStart=null;paint()};
 root.querySelector('[data-reset-view]').onclick=()=>{const positions=[g,...Object.values(sources).filter(s=>s.visible)];const extent=Math.max(25000,...positions.map(p=>Math.max(Math.abs(p.x),Math.abs(p.y))));zoom=Math.max(1,Math.min(12,range/(extent*1.35)));viewX=300-300/zoom;viewY=170-170/zoom;paint()};
 root.querySelectorAll('[data-handle]').forEach(h=>h.onkeydown=e=>{if(!['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();if(h.dataset.handle==='velocity'&&maxSpeed===null||h.dataset.handle==='ownVelocity'&&ownMaxSpeed===null)return;if(sources[h.dataset.handle]){const source=sources[h.dataset.handle],axis=e.key==='ArrowLeft'||e.key==='ArrowRight'?'x':'y',sign=e.key==='ArrowLeft'||e.key==='ArrowDown'?-1:1;source[axis]+=sign*range/50/zoom*(e.shiftKey?.1:1);const d=Math.hypot(source.x,source.y);if(d>range){source.x*=range/d;source.y*=range/d}paint();changed();return}const axis=e.key==='ArrowLeft'||e.key==='ArrowRight'?'x':'y',sign=e.key==='ArrowLeft'||e.key==='ArrowDown'?-1:1;const own=h.dataset.handle==='ownVelocity',velocity=own||h.dataset.handle==='velocity',key=own?(axis==='x'?'ownVx':'ownVy'):(velocity?'v':'')+axis;g[key]+=sign*(velocity?((own?ownMaxSpeed:maxSpeed)||0)/100:range/50/zoom)*(e.shiftKey?.1:1);bound();paint();changed()});
 function stop(){g.vx=g.vy=0;paint();changed()}
 function tangentMotion(){if(maxSpeed===null)return;const v=Math.hypot(g.vx,g.vy)||Math.min(200,maxSpeed),r=Math.hypot(g.x,g.y);g.vx=r?-g.y/r*v:0;g.vy=r?g.x/r*v:v;bound();paint();changed()}
 function changed(){root.dispatchEvent(new CustomEvent('scenario-change'))}
 bound();paint();
 const observer=new ResizeObserver(()=>{if(root.isConnected)paint();else observer.disconnect()});observer.observe(svg);
 return {stop,tangent:tangentMotion,canSetVelocity:()=>maxSpeed!==null,destroy(){observer.disconnect()},setTargetVisible(visible){for(const el of [pos,vel,root.querySelector('.target-vector'),root.querySelector('.target-separation'),root.querySelector('.target-distance-label'),root.querySelector('.canvas-speed-label'),root.querySelector('.canvas-angular-label')])el.style.display=visible?'':'none';root.querySelector('.canvas-hint').hidden=visible||sources.support.visible||sources.hostile.visible;},placeTarget(event){const p=point(event);g.x=(p.x-300)*range/170;g.y=(170-p.y)*range/170;bound();paint()},setSource(key,visible,markup,event){const source=sources[key];source.visible=visible;root.querySelector('.canvas-hint').hidden=pos.style.display!=='none'||sources.support.visible||sources.hostile.visible;if(markup!==undefined)root.querySelector('.scenario-source.'+key).innerHTML=markup;if(event){const p=point(event);source.x=(p.x-300)*range/170;source.y=(170-p.y)*range/170;const d=Math.hypot(source.x,source.y);if(d>range){source.x*=range/d;source.y*=range/d}}paint()},sourceValue(key){const {x,y}=sources[key];return {x,y}},setSpeedLimit(limit,message,ownLimit=null){maxSpeed=Number.isFinite(limit)?Math.max(0,limit):null;ownMaxSpeed=Number.isFinite(ownLimit)?Math.max(0,ownLimit):null;speedStatus=message;if(maxSpeed!==null){if(velocityScale===null&&Math.max(maxSpeed,ownMaxSpeed??0)>0)velocityScale=Math.max(maxSpeed,ownMaxSpeed??0);bound()}paint()},value:()=>({...geometryValues(g),...(velocityScale!==null?{velocityScale}:{}),geometry:{...g},supportGeometry:{x:sources.support.x,y:sources.support.y},hostileGeometry:{x:sources.hostile.x,y:sources.hostile.y}})};
}
