import assert from 'node:assert/strict';
import {skillBonusRows} from './skill-hover.js';
import {createSkillPointDisplay} from './skill-points.js';
const data={attributes:[{id:1,name:'bonus',value:5,unitID:121},{id:2,name:'training',value:99}],effects:[{modifierInfo:[{domain:'itemID',func:'ItemModifier',modifyingAttributeID:280,modifiedAttributeID:1,operation:0}]}]};
assert.equal(skillBonusRows(data,3)[0].value,15);
assert.equal(skillBonusRows(data,1).length,1);
data.attributes[0].value=-5;
assert.equal(skillBonusRows(data,2)[0].value,-10);
data.attributes[0].value=.05;data.attributes[0].unitID=127;
assert.ok(Math.abs(skillBonusRows(data,3)[0].value-15)<1e-10);
assert.deepEqual(skillBonusRows({attributes:data.attributes},3),[]);
const c={skills:[{skillTypeId:1,level:3},{skillTypeId:2,level:2}]};
const points=createSkillPointDisplay(async()=>({complete:false,total:null,items:[{typeId:1,value:8000},{typeId:2,value:null}]}));
assert.equal(points.group(c,new Set([1])),'—');
await new Promise(resolve=>setTimeout(resolve,0));
assert.equal(points.group(c,new Set([1])).replace(/\D/g,''),'8000');
assert.equal(points.group(c,new Set([1,2])),'—');
const snapshot={skills:[],skillSnapshot:{skills:[{skillTypeId:1,skillPoints:8123},{skillTypeId:2,skillPoints:null}]}};
assert.equal(points.group(snapshot,new Set([1])).replace(/\D/g,''),'8123');
assert.equal(points.group(snapshot,new Set([2])),'—');
console.log('Skill bonus and category SP checks passed');
