import assert from 'node:assert/strict';
import {capacitorHtml,capacitorPresentation} from './native-capacitor-view.js';
const result={average:{complete:true,stableFromFullInAverageModel:true,stableFraction:.65,knownNetDrainGjPerSecond:2,peakRechargeGjPerSecond:8,exclusions:[]},recharge:{capacity:100},query:{horizonSeconds:60,initialFraction:1},firstFailedPaymentSeconds:10,firstSupplyStoppedSeconds:null,firstZeroSeconds:null,sources:[],samples:[],supplies:[],sharedCargo:{}};
const report={native:{},capacitorScenario:{result,sources:[]}};
assert.equal(capacitorPresentation(report).summary,'稳定 · 65 %');
assert(!capacitorHtml(report).includes('<select'));
assert(!capacitorHtml(report).includes('<details'));
result.query.horizonSeconds=3600;
assert.equal(capacitorPresentation(report).summary,'稳定 · 65 %');
result.average.complete=false;report.native.capacitor={stableFromFullInAverageModel:true,stableFraction:.9};
assert.equal(capacitorPresentation(report).summary,'暂无法确定');
result.average.complete=true;result.average.stableFromFullInAverageModel=false;
assert.equal(capacitorPresentation(report).summary,'10秒 · 供电不足');
result.firstFailedPaymentSeconds=null;
assert.equal(capacitorPresentation(report).summary,'不稳定 · 续航待确定');
assert(capacitorPresentation(report).detail.conditions.some(([k,v])=>k==='周期查询范围'&&v==='60分'));
result.firstFailedPaymentSeconds=0;
assert.equal(capacitorPresentation(report).summary,'0秒 · 供电不足');
result.events=[{timeUs:0,before:3,payment:{energyReserved:false}}];
assert.deepEqual(capacitorPresentation(report).detail.nativeCapacitor.samples,[{timeSeconds:0,amountGj:3}]);
const missing={native:{capacitorUnavailableReason:'missing',capacitorContributions:[{instanceId:'high-0',state:'unavailable',reason:'EVE_CAPACITOR_EFFECT'}]},snapshot:{modules:[{workspaceSlotKey:'high-0',dogmaTypeId:33400}]}};
assert(capacitorHtml(missing,[{id:33400,name:'堡垒装备 I'}]).includes('缺少 堡垒装备 I 的完整耗电数据'));
console.log('Capacitor: native failure duration is explicit, no invented depletion, stable average preserved, unknowns remain unknown, chart moved to hover.');
