import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const source=readFileSync(new URL('./app-announcements.js',import.meta.url),'utf8');
const {selectAnnouncements}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const now=Date.parse('2026-09-22T00:00:00Z');
const info={id:'info',kind:'info',title:'Notice',body:'Plain text',publishedAt:'2026-09-21T00:00:00Z',startup:true};
const update={...info,id:'update',kind:'update',version:'0.1.4'};
const select=(announcements,version='0.1.3')=>selectAnnouncements({schemaVersion:1,announcements},version,now);
assert.deepEqual(select([info,update]).map(a=>a.id),['info','update']);
assert.equal(select([update],'0.1.4').length,0);
assert.equal(select([update],'0.1.5').length,0);
assert.equal(select([{...update,version:'0.1.3'}],'0.1.3-rc.1').length,1);
assert.equal(select([{...info,expiresAt:'2026-09-22T00:00:00Z'}]).length,0);
assert.equal(select([{...info,publishedAt:'2026-10-01T00:00:00Z'}]).length,0);
assert.equal(select([{...info,minVersion:'0.1.4'}]).length,0);
assert.equal(select([{...info,maxVersion:'0.1.2'}]).length,0);
assert.equal(select([info,info]).length,1);
assert.equal(select([{...info,body:{html:'invalid'}},{...update,version:'garbage'}]).length,0);
assert.throws(()=>selectAnnouncements({schemaVersion:2,announcements:[]},'0.1.3',now));
const feed=JSON.parse(readFileSync(new URL('./website/announcements/feed.json',import.meta.url),'utf8'));
assert.equal(selectAnnouncements(feed,'0.1.3',now).length,1);
console.log('Announcement filtering passed: versions, expiry, schedule, duplicate IDs, malformed feed.');
