import assert from 'node:assert/strict';
import {scaleReading,analysisStatusText} from './analysis-status.js';
import {mountNativeStats,nativeResources} from './nengine-view.js';
import {capacitorHtml} from './native-capacitor-view.js';
assert.equal(scaleReading(null,1000),null);
assert.equal(scaleReading(undefined,1000),null);
assert.equal(scaleReading(0,1000),0);
assert.equal(scaleReading(125000,1000),125);
assert.equal(analysisStatusText({analysisStatus:{legality:'valid',completeness:'partial'}}),'装配合法 · 当前结果不完整');
const report={native:{attributes:{'ship/76':{value:null},'ship/552':{value:null}},weapons:{},resources:[],coverage:[],warnings:[],outputContributions:{items:[],staticBlockers:[]},droneBay:{capacityCubicMeters:1,controlRangeMeters:null,maximumActive:0}},outputSelection:{metric:'nominalCycleDps',status:'empty_selection',groups:[],exclusions:[]},baselineOutputSelection:{metric:'nominalCycleDps'},outputContext:{selection:{contributionIds:[]}},outputBreakdown:Object.fromEntries(['weapons','drones','fighters'].map(k=>[k,{groups:[],exclusions:[]}])),integrationNotices:[],issues:[]};
const host={innerHTML:'',querySelectorAll:()=>[],querySelector:()=>({})};
mountNativeStats(host,report);
assert.match(host.innerHTML,/锁定摘要"><b[^>]*>—<\/b>/);
assert(!host.innerHTML.includes('0 km'));
assert(!host.innerHTML.includes('>0 m<'));
report.native.motion={maximumSpeedMetersPerSecond:0,fromRestTo75PercentSeconds:null,fromRestTo75PercentState:'not_applicable',fromRestTo75PercentUnavailableReason:'ZERO_MAXIMUM_SPEED_NO_FROM_REST_THRESHOLD'};
mountNativeStats(host,report);assert(host.innerHTML.includes('不适用 · 当前最大速度为 0'));assert(!host.innerHTML.includes('>0 s<'));
report.native.capacitorRecharge={capacity:312.5,peakRecharge:8.33};
report.native.capacitorContributions=[{instanceId:'high-0',state:'unavailable',reason:'EVE_CAPACITOR_EFFECT'}];
const partialCap=capacitorHtml(report);assert(partialCap.includes('312.5 GJ'));assert(partialCap.includes('未计入：high-0'));assert(!partialCap.includes('平均稳定电量'));
report.native.resources=[{id:'cpu',remaining:null,capacity:null,withinCapacity:null}];
nativeResources(host,report);assert(!host.innerHTML.includes('<progress'));
console.log('Status presentation: null remains unknown; real zero preserved; unknown resources have no numeric bar');
