from pathlib import Path
p=Path('extract.py');s=p.read_text(encoding='utf-8-sig');s=s.replace("groups={t['_key']", "effects={t['_key']:[e['effectID'] for e in t.get('dogmaEffects',[])] for l in (root/'typeDogma.jsonl').open(encoding='utf-8') if (t:=json.loads(l))['_key'] in ids}\ngroups={t['_key']");s=s.replace("attrs=dogma.get(t['_key'],{})", "attrs=dogma.get(t['_key'],{}),effects=effects.get(t['_key'],[])");p.write_text(s,encoding='utf-8')
p=Path('index.html');s=p.read_text(encoding='utf-8');s=s.replace('<div class="panel-title">物品情报</div><div id="info">右键物品 → 查看信息<br>查看真实 SDE 名称和基础属性。</div>','');s=s.replace('<div id="menu"', '<section id="info-window" role="dialog" aria-labelledby="info-title" hidden><div class="info-titlebar"><span id="info-title">物品信息</span><button id="info-close" aria-label="关闭物品信息">×</button></div><div id="info-content"></div></section><div id="menu"');p.write_text(s,encoding='utf-8')
p=Path('app.js');s=p.read_text(encoding='utf-8');s=s.replace("${t?esc(t.name):'空槽 · 拖入装备'}", "${t?esc(t.name):labels[kind]}")
s=s.replace('<span>${slots.filter(s=>s.kind===kind&&s.item).length} / ${counts[kind]}</span></div>', '<span class="slot-limits">${kind===\'high\'?hardpoints():\'\'}<span title="已用槽位 / 总槽位">${slots.filter(s=>s.kind===kind&&s.item).length} / ${counts[kind]}</span></span></div>')
s=s.replace("+`<div class=\"meter\"><label>炮塔挂点<span>${slots.filter(s=>s.kind==='high'&&s.item).length} / ${ship.attrs['102']||0}</span></label></div>`",'')
start=s.index('function showInfo(');end=s.index('function closeMenu',start)
s=s[:start]+'''const hardpointIcons={turret:'<path d="M4 19h16M7 18v-5h10v5M9 13V9l10-6 2 3-10 7M6 9h5"/>',launcher:'<path d="m9 15 6-11 4-2 1 4-6 11-5-2ZM9 11 5 12 3 17l6-2m5 2 1 4 4-5-1-5M7 18l-3 3"/>'};
function hardpoints(){return [['turret','炮塔',42,102],['launcher','导弹发射器',40,101]].map(([icon,name,effect,attr])=>{const used=slots.filter(s=>byId(s.item)?.effects?.includes(effect)).length,total=ship.attrs[attr]||0;return `<span class="hardpoint ${used>total?'over':''}" tabindex="0" title="${name}挂点：${used} / ${total}" aria-label="${name}挂点：${used} / ${total}"><svg viewBox="0 0 24 24" aria-hidden="true">${hardpointIcons[icon]}</svg>${used} / ${total}</span>`}).join('')}
let infoOrigin=null;
function closeInfo(){const panel=$('#info-window');if(panel.hidden)return;panel.hidden=true;if(infoOrigin?.isConnected)infoOrigin.focus({preventScroll:true})}
function showInfo(t){infoOrigin=document.activeElement;const panel=$('#info-window');$('#info-title').textContent='物品信息';const facts=t.kind==='ship'?[['CPU 输出',`${t.attrs['48']} tf`],['能量栅格输出',`${t.attrs['11']} MW`]]:t.kind==='ammo'?[['弹药尺寸',t.attrs['128']||'—']]:[['CPU 需求',`${t.attrs['50']||0} tf`],['能量栅格需求',`${t.attrs['30']||0} MW`]];$('#info-content').innerHTML=`<div class="info-identity">${img(t)}<div><h2>${esc(t.name)}</h2><small>${esc(t.en)}</small></div></div><div class="info-path">${esc(t.path.join(' › '))}</div><div class="info-section">基础属性</div><dl>${facts.map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`).join('')}<div><dt>类型 ID</dt><dd>${t.id}</dd></div></dl><p class="info-footnote">SDE 基础数据 · 未计入装配与角色加成</p>`;panel.hidden=false;if(!panel.style.left){panel.style.left=Math.max(8,(innerWidth-panel.offsetWidth)/2)+'px';panel.style.top=Math.max(8,(innerHeight-panel.offsetHeight)/2)+'px'}clampInfo();$('#info-close').focus({preventScroll:true});say(`查看信息 · ${t.name}`)}
function clampInfo(){const p=$('#info-window');if(p.hidden)return;const r=p.getBoundingClientRect();p.style.left=Math.max(8,Math.min(r.left,innerWidth-r.width-8))+'px';p.style.top=Math.max(8,Math.min(r.top,innerHeight-r.height-8))+'px'}
$('#info-close').onclick=closeInfo;
$('.info-titlebar').onpointerdown=e=>{if(e.target.closest('button')||e.button!==0)return;e.preventDefault();const bar=e.currentTarget,p=$('#info-window'),r=p.getBoundingClientRect(),dx=e.clientX-r.left,dy=e.clientY-r.top;bar.setPointerCapture(e.pointerId);bar.onpointermove=ev=>{p.style.left=ev.clientX-dx+'px';p.style.top=ev.clientY-dy+'px';clampInfo()};bar.onpointerup=bar.onpointercancel=()=>{bar.onpointermove=null;bar.onpointerup=null;bar.onpointercancel=null}};
window.addEventListener('resize',clampInfo);
''' + s[end:]
s=s.replace("if(e.key==='Escape'){closeMenu();clearDrag()}", "if(e.key==='Escape'){if(!$('#menu').hidden)closeMenu();else closeInfo();clearDrag()}")
p.write_text(s,encoding='utf-8')
p=Path('style.css');s=p.read_text(encoding='utf-8');s+='''
.slot-limits{display:flex;align-items:center;gap:16px;letter-spacing:0}.hardpoint{display:inline-flex;align-items:center;gap:5px;font-variant-numeric:tabular-nums}.hardpoint svg{width:19px;height:19px;fill:none;stroke:currentColor;stroke-width:1.5;stroke-linecap:round;stroke-linejoin:round}.slot-limits>span:last-child{border-left:1px solid var(--line);padding-left:14px}
#info-window{position:fixed;z-index:90;width:420px;max-width:calc(100vw - 16px);max-height:calc(100vh - 16px);overflow:auto;background:var(--panel);border:1px solid #52727e;box-shadow:0 20px 80px #0009;color:var(--text)}.info-titlebar{display:flex;align-items:center;justify-content:space-between;padding:8px 10px 8px 16px;background:var(--row);border-bottom:1px solid var(--line);cursor:move;touch-action:none;user-select:none}.info-titlebar button{font-size:23px;line-height:1;padding:4px 8px;border-color:transparent}.info-titlebar button:hover{color:var(--danger);border-color:var(--danger)}#info-content{padding:20px}.info-identity{display:flex;align-items:center;gap:16px}.info-identity img{width:64px;height:64px}.info-identity h2{font-size:17px;font-weight:500;margin:0 0 5px}.info-identity small,.info-path,.info-footnote{color:var(--muted);font-size:11px}.info-path{padding:18px 0;line-height:1.8}.info-section{font-size:12px;color:var(--accent);border-bottom:1px solid var(--line);padding-bottom:9px}#info-content dl{margin:8px 0 20px}#info-content dl>div{display:flex;justify-content:space-between;padding:9px 0;border-bottom:1px solid var(--line)}#info-content dt{color:var(--muted)}#info-content dd{margin:0}.info-footnote{margin-bottom:0}
''';p.write_text(s,encoding='utf-8')
