from pathlib import Path
p=Path('item-info.js');s=p.read_text(encoding='utf-8');a=s.index('const categoryNames=');b=s.index('\nconst projected',a);s=s[:a]+"const categoryNames={1:'装配',2:'护盾',3:'装甲',4:'结构',5:'电容',6:'锁定',7:'通用',8:'技能要求',9:'其他',10:'无人机',17:'速度与航行',20:'远程支援',21:'目标标记',22:'能量中和',23:'电子反制',24:'感应抑阻',25:'目标干扰',26:'跟踪扰断',27:'跃迁扰断',28:'停滞缠绕',29:'炮塔',30:'导弹',34:'铁骑舰载机能力',36:'电子战抗性',37:'加成',38:'铁骑舰载机属性',39:'超级武器',40:'机库与舱室',51:'采矿',52:'热量'};"+s[b:];p.write_text(s,encoding='utf-8')
p=Path('app.js');s=p.read_text(encoding='utf-8');s="import {renderItemInfo} from './item-info.js';\n"+s;a=s.index('function showInfo(');b=s.index('function clampInfo()',a)
s=s[:a]+'''let infoRequest=0;
async function showInfo(t,slotKey=null){infoOrigin=document.activeElement;const request=++infoRequest,panel=$('#info-window'),captured=currentFit(),selected=slotKey?captured.slots.find(s=>s.key===slotKey):null;$('#info-title').textContent=t.path.join(' › ');$('#info-title').title=t.path.join(' › ');$('#info-content').innerHTML='<p class="profile-note">正在读取物品属性…</p>';panel.hidden=false;if(!panel.style.left){panel.style.left=Math.max(8,(innerWidth-panel.offsetWidth)/2)+'px';panel.style.top='100px'}clampInfo();$('#info-close').focus({preventScroll:true});
 try{const [data,calculation]=await Promise.all([api('items/'+t.id),selected?api('analyze',captured):Promise.resolve(null)]);if(request!==infoRequest||panel.hidden)return;let computed=null;
 if(selected&&calculation){const group=selected.kind==='rig'?calculation.snapshot.rigs:calculation.snapshot.modules;const siblings=captured.slots.filter(s=>s.kind===selected.kind&&s.item===selected.item),index=siblings.findIndex(s=>s.key===selected.key);computed=group.filter(m=>m.dogmaTypeId===selected.item)[index];if(t.kind==='ammo')computed=computed?.charge||null}
 renderItemInfo($('#info-content'),t,data,computed,catalog,`${captured.characterName||'无技能'} · ${selected?stateLabels[moduleState(selected)]||'被动':''}`);clampInfo();say('已读取物品详情');
 }catch(e){if(request===infoRequest&&!panel.hidden)$('#info-content').innerHTML=`<p class="notice">${esc(e.message)}</p>`}
}
'''+s[b:];s=s.replace("['查看信息',()=>showInfo(t)]", "['查看信息',()=>showInfo(t,s?.key)]");p.write_text(s,encoding='utf-8')
