using EdenOS.Application.Fitting;
using EdenOS.Contracts.Fitting;
using System.Text.Json.Serialization;
var builder=WebApplication.CreateBuilder(args);
builder.Services.ConfigureHttpJsonOptions(o=>o.SerializerOptions.Converters.Add(new JsonStringEnumConverter()));
var sde=Environment.GetEnvironmentVariable("FITLAB_SDE_ROOT") ?? throw new Exception("Missing SDE path");
var data=Environment.GetEnvironmentVariable("FITLAB_ENGINE_STATE") ?? throw new Exception("Missing state path");
var key=Environment.GetEnvironmentVariable("FITLAB_ENGINE_KEY") ?? throw new Exception("Missing session key");
builder.Services.AddSingleton(new InMemoryFitService(TimeProvider.System,sde,data,dogmaRuleSetJsonPath:Path.Combine(sde,"dogma-rules.json")));
var app=builder.Build();
app.Use(async (context,next)=>{if(context.Request.Headers["X-FitLab-Key"]!=key){context.Response.StatusCode=403;return;}await next();});
app.MapGet("/health",()=>Results.Ok(new{ready=true}));
app.MapPost("/api/actions/ImportFitText",(ImportFitTextRequest input,InMemoryFitService service)=>service.ImportText(input));
app.MapPost("/api/actions/ValidateFit",(ValidateFitRequest input,InMemoryFitService service)=>service.Validate(input));
app.Run();
