const {app,BrowserWindow,protocol,net,shell,dialog,ipcMain}=require('electron');
const {spawn,spawnSync}=require('node:child_process');
const fs=require('node:fs');const path=require('node:path');const crypto=require('node:crypto');const http=require('node:http');const tcp=require('node:net');
protocol.registerSchemesAsPrivileged([{scheme:'fitlab',privileges:{standard:true,secure:true,supportFetchAPI:true,corsEnabled:true,stream:true}}]);
app.setName('EVE FitLab');
const localRoot=process.env.FITLAB_TEST_ROOT||path.join(process.env.LOCALAPPDATA||app.getPath('appData'),'EVE-FitLab');fs.mkdirSync(localRoot,{recursive:true});
app.setPath('userData',path.join(localRoot,'Browser'));
const children=[];let win,quitting=false,callbackServer,oauthCookie='',apiPort;const apiKey=crypto.randomBytes(32).toString('hex'),engineKey=crypto.randomBytes(32).toString('hex');
if(!app.requestSingleInstanceLock()){app.quit()}else{
app.on('second-instance',()=>{if(win){if(win.isMinimized())win.restore();win.show();win.focus()}});
app.on('window-all-closed',()=>app.quit());
app.on('before-quit',()=>{quitting=true;callbackServer?.close();for(const child of children){if(child.exitCode===null)spawnSync('taskkill',['/PID',String(child.pid),'/T','/F'],{windowsHide:true,stdio:'ignore'})}});
app.whenReady().then(start).catch(error=>{dialog.showErrorBox('EVE FitLab 启动失败',error.message+'\n日志目录：'+path.join(localRoot,'Logs'));app.quit()});
}
async function freePort(){return await new Promise((resolve,reject)=>{const s=tcp.createServer();s.on('error',reject);s.listen(0,'127.0.0.1',()=>{const port=s.address().port;s.close(()=>resolve(port))})})}
function child(exe,args,env,label){const logs=path.join(localRoot,'Logs');fs.mkdirSync(logs,{recursive:true});const file=fs.openSync(path.join(logs,label+'.log'),'w');const p=spawn(exe,args,{env:{...process.env,...env},windowsHide:true,stdio:['ignore',file,file],cwd:path.dirname(exe)});fs.closeSync(file);children.push(p);p.on('error',e=>{if(!quitting){dialog.showErrorBox('后台服务启动失败',e.message);app.quit()}});p.on('exit',code=>{if(!quitting){dialog.showErrorBox('后台服务已停止',label+' 意外退出（'+code+'）。请重新打开应用。');app.quit()}});return p}
async function ready(url,key){const deadline=Date.now()+90000;while(Date.now()<deadline){try{const r=await fetch(url,{headers:{'X-FitLab-Key':key},signal:AbortSignal.timeout(2000)});if(r.ok)return}catch{}await new Promise(r=>setTimeout(r,250))}throw Error('后台计算服务未能就绪。')}
async function external(url){const u=new URL(url);if(['https:','http:','mailto:'].includes(u.protocol))await shell.openExternal(url)}
async function ensureCallback(){if(callbackServer)return;const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://127.0.0.1:5207');if(u.pathname!=='/api/eve/callback'){res.writeHead(404);res.end();return}const result=await fetch('http://127.0.0.1:'+apiPort+u.pathname+u.search,{headers:{'X-FitLab-Key':apiKey,Cookie:oauthCookie},redirect:'manual'});const location=result.headers.get('location')||'/#characters?authError=1';await win.loadURL('fitlab://app/'+location.slice(location.indexOf('#')));win.show();win.focus();res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Referrer-Policy':'no-referrer'});res.end('<title>EVE FitLab</title><p>授权流程已结束，请返回 EVE FitLab。</p>');oauthCookie='';server.close();callbackServer=null}catch{res.writeHead(500);res.end('Authorization failed. Return to EVE FitLab.')}});await new Promise((resolve,reject)=>{server.once('error',()=>reject(Error('官网授权回调端口 5207 被占用，请先关闭正在运行的 FitLab 网页开发服务。')));server.listen(5207,'127.0.0.1',resolve)});callbackServer=server}
async function start(){
 const resources=app.isPackaged?process.resourcesPath:path.join(__dirname,'build');
 let state=path.join(localRoot,'Data');const config=path.join(localRoot,'storage.json');if(fs.existsSync(config))state=JSON.parse(fs.readFileSync(config,'utf8')).directory;fs.mkdirSync(state,{recursive:true});
 win=new BrowserWindow({width:1280,height:900,minWidth:920,minHeight:650,show:false,backgroundColor:'#090e13',title:'EVE FitLab',icon:app.isPackaged?path.join(resources,'icon.ico'):path.join(__dirname,'icon.ico'),autoHideMenuBar:true,titleBarStyle:'hidden',titleBarOverlay:{color:'#090e13',symbolColor:'#d3e0e9',height:68},webPreferences:{preload:path.join(__dirname,'preload.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:true,spellcheck:false}});
 win.removeMenu();win.webContents.setWindowOpenHandler(({url})=>{external(url);return {action:'deny'}});win.webContents.on('will-navigate',(e,url)=>{if(!url.startsWith('fitlab://app/')){e.preventDefault();external(url)}});
 win.webContents.on('before-input-event',(e,input)=>{if(input.key==='F12'||input.control&&['r','l','u'].includes(input.key.toLowerCase())||input.control&&input.shift&&['i','j'].includes(input.key.toLowerCase()))e.preventDefault()});
 win.on('page-title-updated',e=>e.preventDefault());win.webContents.session.setPermissionRequestHandler((contents,permission,callback)=>callback(contents===win.webContents&&permission==='clipboard-sanitized-write')); 
 ipcMain.on('desktop-theme',(event,light)=>{if(event.sender===win.webContents)win.setTitleBarOverlay({color:light?'#dce4e8':'#090e13',symbolColor:light?'#203540':'#d3e0e9',height:68})});
 ipcMain.handle('choose-data-folder',async(event)=>{if(event.sender!==win.webContents)return null;const result=await dialog.showOpenDialog(win,{title:'选择数据存储目录',properties:['openDirectory','createDirectory']});return result.canceled?null:result.filePaths[0]});
 await win.loadFile(path.join(__dirname,'splash.html'));win.show();
 const enginePort=await freePort();apiPort=await freePort();
 child(path.join(resources,'engine','FitLab.Engine.exe'),['--urls','http://127.0.0.1:'+enginePort],{FITLAB_SDE_ROOT:path.join(resources,'sde'),FITLAB_ENGINE_STATE:path.join(state,'engine','dogma-cache'),FITLAB_ENGINE_KEY:engineKey},'engine');
 await ready('http://127.0.0.1:'+enginePort+'/health',engineKey);
 child(path.join(resources,'backend','FitLab.Backend.exe'),[],{FITLAB_WEB_ROOT:path.join(resources,'web'),FITLAB_DEFAULT_STATE:state,FITLAB_API_PORT:String(apiPort),FITLAB_ENGINE_URL:'http://127.0.0.1:'+enginePort,FITLAB_API_KEY:apiKey,FITLAB_ENGINE_KEY:engineKey,FITLAB_STORAGE_CONFIG:path.join(localRoot,'storage.json')},'backend');
 await ready('http://127.0.0.1:'+apiPort+'/api/health',apiKey);
 protocol.handle('fitlab',async request=>{try{const url=new URL(request.url);if(url.host!=='app')return new Response('Forbidden',{status:403});if(url.pathname==='/api/eve/login')await ensureCallback();const headers={'Content-Type':request.headers.get('Content-Type')||'application/json','X-FitLab-Key':apiKey,Origin:'http://127.0.0.1:'+apiPort};const response=await net.fetch('http://127.0.0.1:'+apiPort+url.pathname+url.search,{method:request.method,headers,body:['GET','HEAD'].includes(request.method)?undefined:await request.arrayBuffer(),redirect:'manual'});if(url.pathname==='/api/eve/login')oauthCookie=(response.headers.get('set-cookie')||'').split(';')[0];const out=new Headers(response.headers);out.delete('set-cookie');out.set('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' https: data: blob:; font-src 'self' https:; connect-src 'self'; object-src 'none'; base-uri 'self'; frame-src 'none'");return new Response(response.body,{status:response.status,headers:out})}catch(e){return new Response(JSON.stringify({error:e.message}),{status:503,headers:{'Content-Type':'application/json'}})}});
 await win.loadURL('fitlab://app/#library');
 if(process.argv.includes('--smoke-test')){const out=path.join(localRoot,'desktop-smoke.json');try{await win.webContents.executeJavaScript(`new Promise((resolve,reject)=>{let i=0;const t=setInterval(()=>{if(document.querySelector('#manage-characters')){clearInterval(t);resolve(true)}else if(++i>120){clearInterval(t);reject(Error('UI timeout'))}},250)})`);const result=await win.webContents.executeJavaScript(`(async()=>{const chars=await fetch('/api/characters').then(r=>r.json());const r=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({shipId:587,name:'Desktop smoke',slots:[],skills:chars.find(c=>c.id==='all5').skills})}).then(r=>r.json());return {title:document.title,characters:chars.length,cpu:r.attributes.cpuAvailable,desktop:!!window.fitlabDesktop}})()`);try{await win.webContents.capturePage().then(img=>fs.writeFileSync(path.join(localRoot,'desktop-smoke.png'),img.toPNG()))}catch(e){result.screenshotError=e.message}const unauthorized=await fetch('http://127.0.0.1:'+apiPort+'/api/library');result.unauthorizedStatus=unauthorized.status;fs.writeFileSync(out,JSON.stringify(result,null,2))}catch(e){fs.writeFileSync(out,JSON.stringify({error:e.message}))}app.quit()}
}
